// ╔════════════════════════════════════════════════════════════════════════════╗
// ║  BIG CHEF — Definição do Flavor                                           ║
// ║                                                                           ║
// ║  Cores, imagens, sombras, configuração e textos do sistema Big Chef.      ║
// ║  Inclui overrides por plataforma (desktop-local, desktop-online, web).    ║
// ╚════════════════════════════════════════════════════════════════════════════╝

import type { Flavor } from "./types";

// ── URLs externas ───────────────────────────────────────────────────────────

const URL_APP_STORE = "https://apps.apple.com/br/app/grandchef-2-0-para-atendentes/id1548121357";
const URL_PLAY_STORE = "https://play.google.com/store/apps/details?id=br.com.grandchef.app";

export const bigchef: Flavor = {
  id: "bigchef",

  // ┌──────────────────────────────────────────────────────────────────────────┐
  // │  CORES                                                                   │
  // └──────────────────────────────────────────────────────────────────────────┘

  cores: {
    primaria: "#FF7A00",
    primariaEscura: "#FF4500",
    primariaClara: "#FFF1E6",
    destaque: "#16A34A",
    escura: "#052E16",
    clara: "#FFFFFF",
    borda: "#E5E7EB",
    textoSuave: "#4B5563",
    textoDesabilitado: "#9CA3AF",
    secundaria: "#FFF1E6",
  },

  // ┌──────────────────────────────────────────────────────────────────────────┐
  // │  IMAGENS                                                                 │
  // └──────────────────────────────────────────────────────────────────────────┘
  imagens: {
    gifHeroi: "https://gcsite-assets.grandchef.com.br/images/gerenciamento_conteudo/68de835d93888.gif",
    preVisualizacaoPainel: "https://www.grandchef.com.br/img/home/dashboard-sistema-grandchef.webp",
    simulacaoWhatsapp: "https://gcsite-assets.grandchef.com.br/images/home/bg-chatbot.svg",
    depoimento1: "https://gcsite-assets.grandchef.com.br/images/home/aspas.svg",
    aiqfome: "https://aiqfome.com/assets/images/logo.svg",
    ifood: "https://www.ifood.com.br/static/images/logo.svg",
  },

  // ┌──────────────────────────────────────────────────────────────────────────┐
  // │  SOMBRAS                                                                 │
  // └──────────────────────────────────────────────────────────────────────────┘
  sombras: {
    cabecalho: "0 4px 30px rgba(0,0,0,0.05)",
    imagemPainel: "0 20px 50px rgba(0,0,0,0.1)",
    ctaPadrao: "0 8px 20px rgba(255,122,0,0.3)",
    ctaHover: "0 8px 25px rgba(255,122,0,0.4)",
    botaoHeroiPrimario: "0 10px 40px rgba(255,122,0,0.4)",
    botaoPreco: "0 10px 30px rgba(255,122,0,0.3)",
    botaoPrecoHover: "0 10px 35px rgba(255,122,0,0.4)",
    cardFuncionalidade: "0 10px 40px rgba(255,122,0,0.08)",
    planoSelecionado: "0 6px 20px rgba(255,122,0,0.3)",
  },

  // ┌──────────────────────────────────────────────────────────────────────────┐
  // │  CONFIGURAÇÃO                                                              │
  // └──────────────────────────────────────────────────────────────────────────┘
  configuracao: {
    nome: "Big Chef",
    nomePro: "Big Chef Pro",
    slogan: "Sistema para Restaurantes",
    nomeEmpresa: "Word System Desenvolvimento de Sistemas LTDA",
    descricao: "Sistema de gestão completo para bares, restaurantes, lanchonetes e delivery.",
    logo: "https://bigchef.com.br/sistema/apis_restaurantes/imagens/logo_big_chef.png",
    logoColorida: "https://bigchef.com.br/sistema/apis_restaurantes/imagens/logo_big_chef.png",
    diasTeste: 10,

    secoes: ['heroi', 'appGarcom', 'funcionalidades', 'estatisticas', 'suporte', 'contato', 'chamadaFinal'],
    cabecalho: true,
    rodape: true,

    // Layout clássico centralizado do Big Chef
    variantesInicio: {
      heroi: 'lateral',
      appGarcom: 'compacto',
      funcionalidades: 'destaque',
      estatisticas: 'claro',
      suporte: 'padrao',
      contato: 'padrao',
      chamadaFinal: 'escuro',
    },

    // ── Configuração por plataforma (página inicial) ───────────────────────
    // Cada plataforma sobrescreve APENAS textos (o design é único para todas).
    // O que não for definido aqui herda do nível raiz acima.
    plataformas: {
      // Desktop Local → textos focados na instalação local e performance nativa
      'desktop-local': {
        nome: 'Big Chef Desktop',
        slogan: 'Performance máxima instalado no seu computador',
        descricao: 'Instale o Big Chef no seu computador e tenha o sistema mais rápido e completo para a operação do seu restaurante.',
        menus: {
          funcionalidades: {
            rotulo: "Funcionalidades",
            prefixoRota: "/funcionalidades",
            itens: [
              { rotulo: "Frente de Caixa (PDV)", slug: "frente-de-caixa-pdv" },
              { rotulo: "Mesas e Comandas", slug: "mesas-e-comandas" },
              { rotulo: "Financeiro", slug: "financeiro" },
              { rotulo: "Emissão Fiscal", slug: "emissao-fiscal" },
              { rotulo: "Relatórios Gerenciais", slug: "relatorios-gerenciais" },
            ],
          },
        },
        textos: {
          heroi: {
            selo: 'Sistema instalado no seu computador',
            tituloAntes: 'O sistema mais rápido para',
            tituloDestaque: 'o seu restaurante',
            subtitulo: 'Instale o Big Chef no seu computador e tenha a operação mais rápida e estável do mercado. PDV, mesas, delivery e fiscal — tudo nativo e sem depender de internet.',
            ctaPrimario: 'Começar {trialDays} dias grátis',
            ctaSecundario: 'Ver sistema funcionando',
          },
          appGarcom: {
            selo: 'Aplicativo Nativo',
            titulo: 'O garçom anota, a cozinha',
            tituloDestaque: 'já prepara.',
            subtitulo: 'O app do garçom se conecta ao sistema instalado no computador pela rede Wi-Fi local. Pedidos chegam instantaneamente na impressora da cozinha.',
            recursos: [
              { titulo: 'Pedidos pela rede local', descricao: 'Envio direto pela Wi-Fi do restaurante — ultra-rápido e sem depender de internet.' },
              { titulo: 'Fechamento no caixa', descricao: 'Divida contas e registre gorjetas com os pedidos já integrados na máquina do caixa.' },
            ],
          },
          funcionalidades: {
            titulo: 'Performance nativa para sua operação',
            subtitulo: 'Sistema instalado no computador com velocidade máxima e funcionamento offline.',
            cartoes: [
              { icone: '⚡', titulo: 'Velocidade Nativa', descricao: 'O sistema roda direto no seu computador — sem lentidão de navegador ou dependência de internet.' },
              { icone: '🏪', titulo: 'PDV Ultra-Rápido', descricao: 'Frente de caixa com leitura de código de barras, balanças e operação instantânea.' },
              { icone: '🧾', titulo: 'Mesas e Comandas', descricao: 'Controle detalhado do salão com comandas individuais e divisão de contas ágil.' },
              { icone: '🛵', titulo: 'Delivery Integrado', descricao: 'Receba pedidos no seu site próprio e no chatbot — tudo integrado ao caixa.' },
              { icone: '📑', titulo: 'Emissão Fiscal Integrada', descricao: 'NFC-e e NF-e geradas diretamente pelo sistema, sem precisar de outro software.' },
              { icone: '📊', titulo: 'Relatórios Completos', descricao: 'DRE, ticket médio, pratos mais vendidos e dashboards atualizados na sua tela.' },
            ],
          },
          estatisticas: {
            selo: 'Resultados reais',
            titulo: 'Quem instala o Big Chef não volta atrás',
            itens: [
              { valor: '3.200+', rotulo: 'Restaurantes ativos', icone: '🏪' },
              { valor: '98%', rotulo: 'Taxa de satisfação', icone: '⭐' },
              { valor: '40%', rotulo: 'Redução de erros', icone: '📉' },
              { valor: '10 anos', rotulo: 'No mercado', icone: '🏆' },
            ],
            depoimentos: [
              {
                citacao: 'Antes eu perdia pedido toda sexta à noite. Com o Big Chef instalado, a cozinha já recebe tudo na hora e o caixa fecha sozinho.',
                nome: 'Marcos Aurélio',
                papel: 'Dono — Churrascaria do Marcos, SP',
                iniciais: 'MA',
              },
              {
                citacao: 'A emissão de NFC-e integrada economizou horas do meu contador. E o sistema é muito rápido por rodar direto na máquina.',
                nome: 'Sabrina Fonseca',
                papel: 'Gerente — Bistrô da Villa, RJ',
                iniciais: 'SF',
              },
              {
                citacao: 'Mesmo quando a internet cai, o Big Chef continua funcionando. Para delivery pesado, não tem igual.',
                nome: 'Rafael Teixeira',
                papel: 'Sócio — Pizza da Hora, BH',
                iniciais: 'RT',
              },
            ],
          },
          suporte: {
            selo: 'Suporte humanizado',
            titulo: 'Você nunca fica sozinho',
            subtitulo: 'Nosso time acessa seu computador remotamente para resolver qualquer problema na hora — sem você precisar explicar nada.',
            cartoes: [
              {
                icone: '📞',
                titulo: 'Suporte por WhatsApp',
                descricao: 'Fale com um especialista via WhatsApp sem burocracia e receba respostas rápidas no seu celular.',
              },
              {
                icone: '💻',
                titulo: 'Acesso Remoto',
                descricao: 'Nosso time acessa seu computador remotamente para resolver qualquer problema na hora.',
                destaque: true,
                rotuloDestaque: 'exclusivo',
              },
              {
                icone: '🎓',
                titulo: 'Treinamento Presencial',
                descricao: 'Onboarding completo com a equipe de implantação para você e sua equipe dominarem o sistema desde o dia 1.',
              },
            ],
            tituloHorario: 'Horário de atendimento',
            rotuloDomingo: 'Domingo e feriados',
            valorDomingo: 'Plantão',
            notaDomingo: 'Urgências via WhatsApp',
            notaSuporteCompleto: 'Suporte completo',
          },
          contato: {
            selo: 'Fale com a gente',
            titulo: 'Quer instalar o Big Chef no seu restaurante?',
            subtitulo: 'Tem dúvidas sobre instalação, requisitos do computador ou como funciona o sistema desktop? Nossa equipe mostra tudo ao vivo.',
            rotuloWhatsapp: 'WhatsApp Comercial',
            notaWhatsapp: 'Resposta em minutos no horário de atendimento',
            rotuloEmail: 'E-mail',
            textoBotaoFormulario: 'Enviar mensagem via WhatsApp',
            notaFormulario: 'Ao enviar, você será redirecionado ao WhatsApp com os dados preenchidos.',
          },
          chamadaFinal: {
            selo: 'Sem cartão de crédito',
            titulo: 'Pronto para instalar o Big Chef?',
            subtitulo: 'Baixe agora e teste por {trialDays} dias grátis com todos os módulos ativados, sem compromisso.',
            ctaPrimario: 'Começar {trialDays} dias grátis',
            ctaSecundario: 'Ver planos e preços',
          },
          cadastro: {
            seloTeste: 'dias grátis · sem cartão',
            tituloFormulario: 'Crie sua conta no Big Chef Desktop',
            subtituloFormulario: 'Preencha os dados e baixe o sistema para instalar no seu computador.',
            campoEstabelecimento: 'Nome do estabelecimento',
            placeholderCampoEstabelecimento: 'Ex: Restaurante da Família',
            seloRiscoLateral: 'Sem risco',
            tituloLateral: 'Performance máxima no seu computador!',
            itensLateral: [
              'Sem precisar cadastrar cartão de crédito',
              'Acesso a **todos os módulos** durante o teste',
              'Sistema nativo com **performance máxima**',
              'Funciona **mesmo sem internet**',
              'Cancele quando quiser, sem burocracia',
            ],
            rotuloModulosLateral: 'Módulos inclusos no teste:',
            modulosLateral: ['PDV Rápido', 'Mesas', 'Delivery', 'Comandas', 'NFC-e / NF-e', 'Financeiro', 'App Garçom', 'Relatórios'],
          },
          download: {
            tituloSecao: 'Baixar o Big Chef Desktop',
            prefixoOsDetectado: 'Detectamos que você usa',
            osDesconhecido: 'Escolha sua plataforma abaixo',
            prefixoBotaoDownload: 'Baixar para',
            botaoOutrasPlataformas: 'Baixar para outra plataforma',
            tituloPassos: 'Como começar em 3 passos',
            passos: [
              { titulo: 'Baixe e instale', descricao: 'Clique no botão acima, baixe o instalador e execute. A instalação leva menos de 2 minutos.' },
              { titulo: 'Faça login', descricao: 'Abra o sistema e entre com seu e-mail e senha. Seus módulos já estão liberados.' },
              { titulo: 'Configure seu restaurante', descricao: 'Cadastre produtos, mesas, impressoras e comece a vender.' },
            ],
            tituloRequisitos: 'Requisitos do sistema',
            rotuloDesktop: 'Computador (PDV / Painel)',
            rotuloMobile: 'Celular (App Garçom)',
          },
          planos: {
            seloHeroi: 'dias grátis, sem cartão de crédito',
            tituloHeroi: 'Big Chef Desktop: o plano ideal para seu restaurante',
            subtituloHeroi: 'Instale no computador e teste por {trialDays} dias grátis, sem cadastro de cartão. Performance nativa com todos os módulos liberados!',
            botaoEscolher: 'Comece Agora',
            botaoPlanoAtual: 'Plano Atual',
            rotuloMaisVendido: 'Mais vendido',
            linkCompararPlanos: 'Comparar os Planos',
            prefixoEconomize: 'Economize',
            sufixoMes: '/mês',
            sufixoTotal: '/total',
            rotuloUsuarios: 'Usuários',
            rotuloPainelAdmin: 'Painel Administrativo',
            rotuloAppMobile: 'App Android e iOS',
            rotuloEspacoIlimitado: 'Espaço ilimitado',
            seloComparativo: 'Comparativo',
            tituloComparativo: 'Compare os planos e descubra a solução ideal para seu restaurante',
            dicaRolarMobile: 'Role para comparar os planos',
            botaoComecePelaTabela: 'Comece grátis',
          },
          paginasFuncionalidades: {
            'frente-de-caixa-pdv': {
              titulo: 'Frente de Caixa (PDV) — Desktop',
              subtitulo: 'Velocidade nativa no atendimento presencial',
              descricao: 'O PDV do Big Chef Desktop opera direto no seu computador com leitura de código de barras, integração com balanças e impressoras térmicas. Funciona mesmo sem internet.',
              icone: '🏪',
              recursos: [
                { titulo: 'Leitura de código de barras', descricao: 'Escaneie produtos instantaneamente sem depender de conexão.', icone: '📷' },
                { titulo: 'Integração com balanças', descricao: 'Peso capturado automaticamente direto no sistema local.', icone: '⚖️' },
                { titulo: 'Múltiplas formas de pagamento', descricao: 'Dinheiro, cartão, Pix e vouchers em uma única venda.', icone: '💳' },
                { titulo: 'Modo offline completo', descricao: 'Venda normalmente sem internet — tudo sincroniza depois.', icone: '📶' },
              ],
            },
            'mesas-e-comandas': {
              titulo: 'Mesas e Comandas — Desktop',
              subtitulo: 'Controle total do salão com performance nativa',
              descricao: 'Gerencie mesas, comandas individuais e divisão de contas com velocidade máxima. O sistema instalado garante resposta instantânea mesmo nos horários de pico.',
              icone: '🧾',
              recursos: [
                { titulo: 'Mapa de mesas visual', descricao: 'Veja o status de cada mesa em tempo real no seu monitor.', icone: '🗺️' },
                { titulo: 'Comandas individuais', descricao: 'Cada cliente com sua comanda, sem risco de erro.', icone: '📝' },
                { titulo: 'Divisão de conta', descricao: 'Divida por igual ou por consumo individual com agilidade.', icone: '➗' },
                { titulo: 'Transferência de mesa', descricao: 'Troque clientes de mesa sem perder pedidos registrados.', icone: '🔄' },
              ],
            },
            'financeiro': {
              titulo: 'Financeiro — Desktop',
              subtitulo: 'Gestão financeira completa instalada no seu computador',
              descricao: 'Controle receitas, despesas, contas a pagar e receber localmente. Seus dados financeiros seguros no seu próprio computador com acesso instantâneo.',
              icone: '💰',
              recursos: [
                { titulo: 'Fluxo de caixa local', descricao: 'Entradas e saídas atualizadas em tempo real no seu computador.', icone: '📊' },
                { titulo: 'Contas a pagar e receber', descricao: 'Organize vencimentos e evite inadimplência com alertas locais.', icone: '📅' },
                { titulo: 'Conciliação bancária', descricao: 'Compare lançamentos do sistema com o extrato do banco.', icone: '🏦' },
                { titulo: 'DRE automático', descricao: 'Demonstrativo de resultados gerado localmente sem latência.', icone: '📈' },
              ],
            },
            'emissao-fiscal': {
              titulo: 'Emissão Fiscal — Desktop',
              subtitulo: 'NFC-e e NF-e com máxima velocidade e estabilidade',
              descricao: 'Emita notas fiscais direto do sistema instalado, com comunicação direta à SEFAZ. Sem depender de navegador ou conexão instável.',
              icone: '📑',
              recursos: [
                { titulo: 'NFC-e automática', descricao: 'Nota de consumidor emitida instantaneamente a cada venda.', icone: '🧾' },
                { titulo: 'NF-e completa', descricao: 'Emissão de nota fiscal eletrônica para fornecedores e clientes.', icone: '📄' },
                { titulo: 'Cancelamento e inutilização', descricao: 'Gerencie notas canceladas e inutilizadas sem burocracia.', icone: '❌' },
                { titulo: 'Relatório fiscal', descricao: 'Consulte todas as notas emitidas com filtros avançados.', icone: '🔍' },
              ],
            },
            'relatorios-gerenciais': {
              titulo: 'Relatórios Gerenciais — Desktop',
              subtitulo: 'Dados estratégicos com velocidade nativa',
              descricao: 'Dashboards e relatórios detalhados processados localmente no seu computador. Ticket médio, produtos mais vendidos, DRE — tudo instantâneo.',
              icone: '📊',
              recursos: [
                { titulo: 'Dashboard em tempo real', descricao: 'Indicadores do dia atualizados sem depender de internet.', icone: '📈' },
                { titulo: 'Ticket médio', descricao: 'Acompanhe o valor médio das vendas por período.', icone: '🎫' },
                { titulo: 'Ranking de produtos', descricao: 'Saiba quais itens mais vendem e otimize seu cardápio.', icone: '🏆' },
                { titulo: 'Relatório por garçom', descricao: 'Meça a performance de cada atendente da sua equipe.', icone: '👤' },
              ],
            },
          },
          paginasSegmentos: {
            'restaurantes': {
              titulo: 'Sistema Desktop para Restaurantes',
              subtitulo: 'Performance nativa para a operação do seu restaurante',
              descricao: 'Com o Big Chef Desktop instalado, seu restaurante opera com velocidade máxima. Do atendimento no salão à gestão financeira, tudo funciona mesmo sem internet.',
              icone: '🍽️',
              beneficios: [
                { titulo: 'Gestão de mesas e comandas', descricao: 'Organize o salão com mapa visual e comandas individuais sem lentidão.', icone: '🗺️' },
                { titulo: 'PDV ultra-rápido', descricao: 'Atendimento no caixa instantâneo com código de barras e balanças.', icone: '🏪' },
                { titulo: 'Funcionamento offline', descricao: 'Continue operando normalmente mesmo sem internet.', icone: '📶' },
                { titulo: 'Emissão fiscal integrada', descricao: 'NFC-e e NF-e emitidas direto do sistema local.', icone: '📑' },
              ],
            },
            'bares-e-baladas': {
              titulo: 'Sistema Desktop para Bares e Baladas',
              subtitulo: 'Velocidade máxima para operações noturnas',
              descricao: 'Gerencie comandas e mesas em alta velocidade com o Big Chef Desktop. Performance nativa ideal para bares, pubs e casas noturnas com grande volume.',
              icone: '🍺',
              beneficios: [
                { titulo: 'Comandas instantâneas', descricao: 'Abertura e fechamento de comandas sem travamentos.', icone: '⚡' },
                { titulo: 'Controle de estoque local', descricao: 'Monitore bebidas e insumos com dados no seu computador.', icone: '📦' },
                { titulo: 'Divisão de conta ágil', descricao: 'Divida por igual ou por consumo com velocidade nativa.', icone: '➗' },
                { titulo: 'App do garçom integrado', descricao: 'Pedidos do celular direto para o bar instantaneamente.', icone: '📱' },
              ],
            },
            'cafeterias': {
              titulo: 'Sistema Desktop para Cafeterias',
              subtitulo: 'Agilidade nativa para o seu café',
              descricao: 'PDV rápido no balcão, controle de insumos e relatórios completos — tudo instalado no seu computador com resposta instantânea.',
              icone: '☕',
              beneficios: [
                { titulo: 'PDV de balcão nativo', descricao: 'Atendimento ultra-rápido no caixa sem depender de internet.', icone: '🏪' },
                { titulo: 'Programa de fidelidade', descricao: 'Fidelize clientes com cartão digital de pontos.', icone: '⭐' },
                { titulo: 'Controle de insumos', descricao: 'Saiba exatamente quanto gasta em cada receita.', icone: '📊' },
                { titulo: 'Relatórios locais', descricao: 'Identifique campeões de venda com relatórios processados na máquina.', icone: '📈' },
              ],
            },
            'dark-kitchens': {
              titulo: 'Sistema Desktop para Dark Kitchens',
              subtitulo: 'Gestão de delivery com performance nativa',
              descricao: 'Automatize pedidos, integre com marketplaces e organize a cozinha com o Big Chef Desktop. Processamento local garante estabilidade total.',
              icone: '🏭',
              beneficios: [
                { titulo: 'Integração com iFood e AiqFome', descricao: 'Receba pedidos de todos os canais direto no seu computador.', icone: '🔗' },
                { titulo: 'Painel de produção local', descricao: 'Organize pedidos por prioridade com velocidade nativa.', icone: '📋' },
                { titulo: 'Operação offline', descricao: 'Continue recebendo e processando pedidos sem internet.', icone: '📶' },
                { titulo: 'Relatório de performance', descricao: 'Tempo de preparo, cancelamentos e mais — processados localmente.', icone: '📊' },
              ],
            },
            'sistema-para-delivery': {
              titulo: 'Sistema Desktop para Delivery',
              subtitulo: 'Delivery profissional com estabilidade nativa',
              descricao: 'Monte seu canal de delivery com cardápio digital e chatbot no WhatsApp. O Big Chef Desktop processa tudo localmente com máxima estabilidade.',
              icone: '🛵',
              beneficios: [
                { titulo: 'Site próprio de delivery', descricao: 'Cardápio online com seu domínio e sua marca.', icone: '🌐' },
                { titulo: 'Chatbot para WhatsApp', descricao: 'Pedidos automáticos pelo WhatsApp integrados ao sistema local.', icone: '💬' },
                { titulo: 'Rastreamento de pedido', descricao: 'Status em tempo real para o cliente.', icone: '📍' },
                { titulo: 'Gestão de entregadores', descricao: 'Controle rotas e atribuições direto do computador.', icone: '🏍️' },
              ],
            },
          },
          parceiros: {
            seloPagina: 'Programa de Parceiros',
            tituloPagina: 'Cresça com o Big Chef Desktop',
            subtituloPagina: 'Seja um parceiro comercial e ganhe comissões recorrentes indicando o ERP desktop com performance nativa para restaurantes.',
            seloSobre: 'Quem somos',
            tituloSobre: 'Conheça a Word System',
            descricaoSobre: 'Desenvolvemos soluções de gestão com performance nativa para restaurantes, bares e delivery há mais de uma década.',
            descricaoEmpresa: 'Especializada no desenvolvimento de ERPs instalados localmente para o setor de alimentação fora do lar.',
            sede: 'Santa Fé — PR, Brasil',
            cnpjLabel: 'Empresa registrada e ativa desde 2016',
            atuacao: 'Todo o território nacional',
            numeros: [
              { valor: '+10', rotulo: 'Anos no mercado', icone: '📅' },
              { valor: '+3.000', rotulo: 'Clientes ativos', icone: '👥' },
              { valor: '+15.000', rotulo: 'Estabelecimentos gerenciados', icone: '🏪' },
              { valor: '24/7', rotulo: 'Suporte disponível', icone: '🎧' },
            ],
            motivosParceiro: [
              'Sistema desktop com performance nativa — diferencial competitivo',
              'Funciona offline, ideal para regiões com internet instável',
              'Mais de 3.000 clientes ativos em todo o Brasil',
              'Alta taxa de conversão e retenção de clientes',
              'Suporte completo com instalação remota inclusa',
              'Comissões recorrentes e previsíveis',
            ],
            vantagens: [
              { icone: '💰', titulo: 'Comissão Recorrente', descricao: 'Receba comissões mensais por cada cliente ativo indicado por você.' },
              { icone: '📦', titulo: 'Material de Apoio', descricao: 'Materiais de marketing e apresentações prontas sobre o ERP desktop.' },
              { icone: '🎓', titulo: 'Treinamento Especializado', descricao: 'Capacitação completa sobre o sistema instalado para vender com confiança.' },
              { icone: '🤝', titulo: 'Suporte Dedicado', descricao: 'Canal direto com nosso time comercial para fechar negócios.' },
              { icone: '📈', titulo: 'Painel do Parceiro', descricao: 'Acompanhe indicações, comissões e desempenho em tempo real.' },
              { icone: '🚀', titulo: 'Sem Investimento Inicial', descricao: 'Torne-se parceiro sem nenhum custo. Cadastre-se e comece.' },
            ],
            comoFunciona: [
              { passo: '1', titulo: 'Cadastre-se', descricao: 'Preencha o formulário com seus dados e aguarde a aprovação.' },
              { passo: '2', titulo: 'Receba seu acesso', descricao: 'Após aprovado, você terá acesso ao painel e materiais de apoio.' },
              { passo: '3', titulo: 'Indique clientes', descricao: 'Compartilhe seu link exclusivo e apresente o Big Chef Desktop.' },
              { passo: '4', titulo: 'Receba comissões', descricao: 'A cada cliente que assinar, você recebe comissão recorrente.' },
            ],
            itensLateral: [
              'Comissão **recorrente** mensal',
              'Material de marketing **exclusivo**',
              'Treinamento **completo** sobre o produto desktop',
              'Suporte **dedicado** do time comercial',
              'Painel para acompanhar **indicações e ganhos**',
              '**Sem investimento** inicial',
            ],
            perfisIdeais: ['Consultores de TI', 'Contadores', 'Vendedores autônomos', 'Empresas de tecnologia', 'Revendedores de software'],
          },
        },
      },

      // Desktop Online → textos voltados para acesso remoto
      'desktop-online': {
        nome: 'Big Chef Desktop Online',
        slogan: 'Seu restaurante acessível de qualquer lugar',
        descricao: 'Gerencie seu restaurante remotamente com o Big Chef Desktop Online. Acesse de qualquer computador com internet.',
        menus: {
          funcionalidades: {
            rotulo: "Funcionalidades",
            prefixoRota: "/funcionalidades",
            itens: [
              { rotulo: "Frente de Caixa (PDV)", slug: "frente-de-caixa-pdv" },
              { rotulo: "Mesas e Comandas", slug: "mesas-e-comandas" },
              // { rotulo: "Chatbot para Delivery", slug: "chatbot-para-delivery" },
              { rotulo: "Financeiro", slug: "financeiro" },
              { rotulo: "Emissão Fiscal", slug: "emissao-fiscal" },
              { rotulo: "Relatórios Gerenciais", slug: "relatorios-gerenciais" },
            ],
          },
        },
        textos: {
          heroi: {
            selo: 'Acesse de qualquer computador',
            tituloAntes: 'Gerencie seu restaurante',
            tituloDestaque: 'de qualquer lugar',
            subtitulo: 'Com o Big Chef Desktop Online, você instala o sistema no seu computador e acessa seus dados na nuvem. Ideal para quem quer mobilidade sem abrir mão de performance.',
            ctaPrimario: 'Começar {trialDays} dias grátis',
            ctaSecundario: 'Ver como funciona',
          },
          appGarcom: {
            selo: 'Aplicativo Nativo',
            titulo: 'Garçom anota, a cozinha',
            tituloDestaque: 'recebe na hora.',
            subtitulo: 'Com o Desktop Online, os pedidos do app são enviados via nuvem — sem depender de rede local. Funciona mesmo com terminais em locais diferentes.',
            recursos: [
              { titulo: 'Pedidos via nuvem', descricao: 'O pedido sai do celular do garçom e chega na cozinha pela internet, sem rede Wi-Fi local obrigatória.' },
              { titulo: 'Fechamento sincronizado', descricao: 'Divida contas e registre gorjetas no celular, com tudo sincronizado automaticamente no caixa.' },
            ],
          },
          funcionalidades: {
            titulo: 'Tudo do Desktop, com a liberdade da nuvem',
            subtitulo: 'O mesmo sistema poderoso, mas com seus dados sincronizados online para acessar de qualquer máquina.',
            cartoes: [
              { icone: '☁️', titulo: 'Dados na Nuvem', descricao: 'Seus dados ficam seguros na nuvem e acessíveis de qualquer computador com o sistema instalado.' },
              { icone: '🔄', titulo: 'Sincronização Automática', descricao: 'Alterações em um terminal são refletidas em todos os outros em tempo real.' },
              { icone: '🏪', titulo: 'PDV Completo', descricao: 'Frente de caixa com leitura de código de barras, balanças e operação ultrarrápida.' },
              { icone: '🧾', titulo: 'Mesas e Comandas', descricao: 'Controle detalhado do salão com divisão de contas e acompanhamento por mesa.' },
              { icone: '📑', titulo: 'Emissão Fiscal Integrada', descricao: 'NFC-e e NF-e geradas diretamente pelo sistema sem precisar de outro software.' },
              { icone: '📊', titulo: 'Relatórios em Tempo Real', descricao: 'Acompanhe DRE, ticket médio e vendas de qualquer lugar com dashboards atualizados.' },
            ],
          },
          estatisticas: {
            selo: 'Resultados reais',
            titulo: 'Quem usa o Desktop Online já viu a diferença',
            itens: [
              { valor: '3.200+', rotulo: 'Restaurantes ativos', icone: '🏪' },
              { valor: '98%', rotulo: 'Taxa de satisfação', icone: '⭐' },
              { valor: '40%', rotulo: 'Redução de erros', icone: '📉' },
              { valor: '10 anos', rotulo: 'No mercado', icone: '🏆' },
            ],
            depoimentos: [
              {
                citacao: 'Tenho duas unidades em cidades diferentes e consigo acompanhar as duas pelo mesmo sistema. O Desktop Online resolveu minha vida.',
                nome: 'Marcos Aurélio',
                papel: 'Dono — Churrascaria do Marcos, SP',
                iniciais: 'MA',
              },
              {
                citacao: 'A sincronização é instantânea. Cadastro um prato na matriz e já aparece na filial. Não volto mais pro sistema antigo.',
                nome: 'Sabrina Fonseca',
                papel: 'Gerente — Bistrô da Villa, RJ',
                iniciais: 'SF',
              },
              {
                citacao: 'Acompanho as vendas do delivery pelo notebook em casa. O Desktop Online me deu liberdade que eu não tinha.',
                nome: 'Rafael Teixeira',
                papel: 'Sócio — Pizza da Hora, BH',
                iniciais: 'RT',
              },
            ],
          },
          suporte: {
            selo: 'Suporte humanizado',
            titulo: 'Suporte remoto e rápido, de qualquer lugar',
            subtitulo: 'Nosso time se conecta ao seu computador remotamente para resolver problemas na hora — mesmo que você esteja longe do restaurante.',
            cartoes: [
              {
                icone: '📞',
                titulo: 'Suporte por WhatsApp',
                descricao: 'Fale com um especialista via WhatsApp de qualquer lugar e receba respostas rápidas.',
              },
              {
                icone: '💻',
                titulo: 'Acesso Remoto',
                descricao: 'Nosso time acessa seu computador remotamente para resolver qualquer problema na hora, esteja você onde estiver.',
                destaque: true,
                rotuloDestaque: 'exclusivo',
              },
              {
                icone: '🎓',
                titulo: 'Treinamento Online',
                descricao: 'Onboarding por videochamada para você e sua equipe dominarem todas as funcionalidades remotamente.',
              },
            ],
            tituloHorario: 'Horário de atendimento',
            rotuloDomingo: 'Domingo e feriados',
            valorDomingo: 'Plantão',
            notaDomingo: 'Urgências via WhatsApp',
            notaSuporteCompleto: 'Suporte completo',
          },
          contato: {
            selo: 'Fale com a gente',
            titulo: 'Quer saber mais sobre o Desktop Online?',
            subtitulo: 'Tem dúvidas sobre sincronização, multi-terminais ou acesso remoto? Nossa equipe está pronta para explicar como funciona para o seu cenário.',
            rotuloWhatsapp: 'WhatsApp Comercial',
            notaWhatsapp: 'Resposta em minutos no horário de atendimento',
            rotuloEmail: 'E-mail',
            textoBotaoFormulario: 'Enviar mensagem via WhatsApp',
            notaFormulario: 'Ao enviar, você será redirecionado ao WhatsApp com os dados preenchidos.',
          },
          chamadaFinal: {
            selo: 'Sem cartão de crédito',
            titulo: 'Pronto para gerenciar de qualquer lugar?',
            subtitulo: 'Teste o Big Chef Desktop Online por {trialDays} dias com todos os módulos, sem compromisso.',
            ctaPrimario: 'Começar {trialDays} dias grátis',
            ctaSecundario: 'Ver planos e preços',
          },
          cadastro: {
            seloTeste: 'dias grátis · sem cartão',
            tituloFormulario: 'Crie sua conta no Big Chef Online',
            subtituloFormulario: 'Preencha os dados e acesse o sistema de qualquer computador com internet.',
            campoEstabelecimento: 'Nome do estabelecimento',
            placeholderCampoEstabelecimento: 'Ex: Restaurante da Família',
            seloRiscoLateral: 'Sem risco',
            tituloLateral: 'Acesse de qualquer lugar!',
            itensLateral: [
              'Sem precisar cadastrar cartão de crédito',
              'Acesso a **todos os módulos** durante o teste',
              'Dados na nuvem com **sincronização automática**',
              'Acesse de **qualquer computador** com internet',
              'Cancele quando quiser, sem burocracia',
            ],
            rotuloModulosLateral: 'Módulos inclusos no teste:',
            modulosLateral: ['PDV Rápido', 'Mesas', 'Delivery', 'Comandas', 'NFC-e / NF-e', 'Financeiro', 'App Garçom', 'Relatórios'],
          },
          download: {
            tituloSecao: 'Baixar o Big Chef Desktop Online',
            prefixoOsDetectado: 'Detectamos que você usa',
            osDesconhecido: 'Escolha sua plataforma abaixo',
            prefixoBotaoDownload: 'Baixar para',
            botaoOutrasPlataformas: 'Baixar para outra plataforma',
            tituloPassos: 'Como começar em 3 passos',
            passos: [
              { titulo: 'Baixe e instale', descricao: 'Clique no botão acima e execute o instalador. A instalação leva menos de 2 minutos.' },
              { titulo: 'Faça login', descricao: 'Entre com seu e-mail e senha. Seus dados já estarão sincronizados na nuvem.' },
              { titulo: 'Configure e sincronize', descricao: 'Configure seu restaurante e acesse de qualquer terminal conectado.' },
            ],
            tituloRequisitos: 'Requisitos do sistema',
            rotuloDesktop: 'Computador (PDV / Painel)',
            rotuloMobile: 'Celular (App Garçom / Delivery)',
          },
          planos: {
            seloHeroi: 'dias grátis, sem cartão de crédito',
            tituloHeroi: 'Big Chef Desktop Online: gerencie de qualquer lugar',
            subtituloHeroi: 'Teste por {trialDays} dias grátis, sem cartão de crédito. Dados na nuvem com acesso remoto de qualquer computador conectado!',
            botaoEscolher: 'Comece Agora',
            botaoPlanoAtual: 'Plano Atual',
            rotuloMaisVendido: 'Mais vendido',
            linkCompararPlanos: 'Comparar os Planos',
            prefixoEconomize: 'Economize',
            sufixoMes: '/mês',
            sufixoTotal: '/total',
            rotuloUsuarios: 'Usuários',
            rotuloPainelAdmin: 'Painel Administrativo',
            rotuloAppMobile: 'App Android e iOS',
            rotuloEspacoIlimitado: 'Espaço ilimitado',
            seloComparativo: 'Comparativo',
            tituloComparativo: 'Compare os planos e escolha a melhor solução para seu restaurante online',
            dicaRolarMobile: 'Role para comparar os planos',
            botaoComecePelaTabela: 'Comece grátis',
          },
          paginasFuncionalidades: {
            'frente-de-caixa-pdv': {
              titulo: 'Frente de Caixa (PDV) — Online',
              subtitulo: 'PDV sincronizado na nuvem em todos os terminais',
              descricao: 'O PDV do Big Chef Desktop Online mantém todas as vendas sincronizadas em tempo real. Opere em múltiplos caixas com dados unificados na nuvem.',
              icone: '🏪',
              recursos: [
                { titulo: 'Sincronização em tempo real', descricao: 'Vendas registradas em um terminal aparecem instantaneamente nos demais.', icone: '🔄' },
                { titulo: 'Múltiplos caixas', descricao: 'Opere vários PDVs simultâneos com estoque e financeiro unificados.', icone: '🖥️' },
                { titulo: 'Múltiplas formas de pagamento', descricao: 'Dinheiro, cartão, Pix e vouchers em uma única venda.', icone: '💳' },
                { titulo: 'Backup automático na nuvem', descricao: 'Seus dados de vendas protegidos automaticamente na nuvem.', icone: '☁️' },
              ],
            },
            'mesas-e-comandas': {
              titulo: 'Mesas e Comandas — Online',
              subtitulo: 'Salão e cozinha sincronizados em tempo real',
              descricao: 'Gerencie mesas e comandas com sincronização instantânea entre terminais. Pedidos feitos no salão chegam à cozinha em tempo real via nuvem.',
              icone: '🧾',
              recursos: [
                { titulo: 'Mapa de mesas sincronizado', descricao: 'Status de cada mesa atualizado em todos os terminais simultaneamente.', icone: '🗺️' },
                { titulo: 'Comandas multi-terminal', descricao: 'Qualquer atendente pode lançar pedidos de qualquer computador.', icone: '📝' },
                { titulo: 'Divisão de conta', descricao: 'Divida por igual ou por consumo com dados unificados.', icone: '➗' },
                { titulo: 'Transferência de mesa', descricao: 'Troque clientes de mesa e a informação atualiza em todos os pontos.', icone: '🔄' },
              ],
            },
            // 'chatbot-para-delivery': {
            //   titulo: 'Chatbot para Delivery — Online',
            //   subtitulo: 'Pedidos online integrados à nuvem em tempo real',
            //   descricao: 'Receba pedidos pelo WhatsApp e site próprio com sincronização automática na nuvem. Acompanhe tudo de qualquer terminal conectado.',
            //   icone: '🛵',
            //   recursos: [
            //     { titulo: 'Cardápio digital na nuvem', descricao: 'Cardápio sempre atualizado e sincronizado em todos os canais.', icone: '📱' },
            //     { titulo: 'Chatbot WhatsApp', descricao: 'Atendimento automático 24h com pedidos sincronizados na nuvem.', icone: '🤖' },
            //     { titulo: 'Acompanhamento multi-terminal', descricao: 'Monitore pedidos de delivery de qualquer computador conectado.', icone: '📍' },
            //     { titulo: 'Integração com iFood e AiqFome', descricao: 'Pedidos de marketplaces sincronizados automaticamente.', icone: '🔗' },
            //   ],
            // },
            'financeiro': {
              titulo: 'Financeiro — Online',
              subtitulo: 'Gestão financeira acessível de qualquer lugar',
              descricao: 'Controle receitas, despesas e fluxo de caixa de qualquer computador conectado. Dados financeiros sempre sincronizados e acessíveis remotamente.',
              icone: '💰',
              recursos: [
                { titulo: 'Fluxo de caixa na nuvem', descricao: 'Entradas e saídas atualizadas e acessíveis de qualquer terminal.', icone: '📊' },
                { titulo: 'Contas a pagar e receber', descricao: 'Gerencie vencimentos remotamente com alertas sincronizados.', icone: '📅' },
                { titulo: 'Conciliação bancária', descricao: 'Compare lançamentos com o extrato bancário de qualquer lugar.', icone: '🏦' },
                { titulo: 'DRE em tempo real', descricao: 'Demonstrativo de resultados sempre atualizado na nuvem.', icone: '📈' },
              ],
            },
            'emissao-fiscal': {
              titulo: 'Emissão Fiscal — Online',
              subtitulo: 'Notas fiscais emitidas de qualquer terminal',
              descricao: 'Emita NFC-e e NF-e de qualquer computador conectado ao Big Chef Desktop Online. Dados fiscais sincronizados e centralizados na nuvem.',
              icone: '📑',
              recursos: [
                { titulo: 'NFC-e de qualquer terminal', descricao: 'Emita nota de consumidor de qualquer caixa conectado.', icone: '🧾' },
                { titulo: 'NF-e centralizada', descricao: 'Emissão de NF-e com dados unificados na nuvem.', icone: '📄' },
                { titulo: 'Cancelamento e inutilização', descricao: 'Gerencie notas canceladas de qualquer computador.', icone: '❌' },
                { titulo: 'Relatório fiscal remoto', descricao: 'Consulte notas emitidas de qualquer lugar com filtros avançados.', icone: '🔍' },
              ],
            },
            'relatorios-gerenciais': {
              titulo: 'Relatórios Gerenciais — Online',
              subtitulo: 'Dados estratégicos acessíveis de qualquer lugar',
              descricao: 'Acompanhe dashboards e relatórios detalhados remotamente. Ticket médio, produtos mais vendidos e DRE — tudo sincronizado na nuvem.',
              icone: '📊',
              recursos: [
                { titulo: 'Dashboard remoto', descricao: 'Indicadores do dia acessíveis de qualquer computador conectado.', icone: '📈' },
                { titulo: 'Ticket médio', descricao: 'Acompanhe o valor médio das vendas mesmo fora do restaurante.', icone: '🎫' },
                { titulo: 'Ranking de produtos', descricao: 'Saiba quais itens mais vendem em tempo real pela nuvem.', icone: '🏆' },
                { titulo: 'Relatório por garçom', descricao: 'Meça a performance de cada atendente remotamente.', icone: '👤' },
              ],
            },
          },
          paginasSegmentos: {
            'restaurantes': {
              titulo: 'Sistema Online para Restaurantes',
              subtitulo: 'Gerencie seu restaurante de qualquer lugar',
              descricao: 'Com o Big Chef Desktop Online, gerencie seu restaurante remotamente. Dados na nuvem, múltiplos terminais sincronizados e acesso de qualquer computador.',
              icone: '🍽️',
              beneficios: [
                { titulo: 'Múltiplos terminais', descricao: 'Opere caixa, salão e cozinha em computadores diferentes, tudo sincronizado.', icone: '🖥️' },
                { titulo: 'Acesso remoto', descricao: 'Acompanhe as vendas e o financeiro mesmo fora do restaurante.', icone: '🌐' },
                { titulo: 'Backup automático', descricao: 'Seus dados protegidos automaticamente na nuvem.', icone: '☁️' },
                { titulo: 'Emissão fiscal sincronizada', descricao: 'NFC-e e NF-e emitidas de qualquer terminal conectado.', icone: '📑' },
              ],
            },
            'bares-e-baladas': {
              titulo: 'Sistema Online para Bares e Baladas',
              subtitulo: 'Múltiplos pontos de venda sincronizados',
              descricao: 'Gerencie comandas e mesas em vários terminais com o Big Chef Desktop Online. Dados sincronizados na nuvem para operações noturnas de alto volume.',
              icone: '🍺',
              beneficios: [
                { titulo: 'Comandas multi-terminal', descricao: 'Qualquer caixa ou garçom registra pedidos — tudo sincronizado.', icone: '⚡' },
                { titulo: 'Estoque em tempo real', descricao: 'Monitore bebidas e insumos com dados unificados na nuvem.', icone: '📦' },
                { titulo: 'Divisão de conta sincronizada', descricao: 'Divida contas de qualquer terminal com dados centralizados.', icone: '➗' },
                { titulo: 'Gestão remota', descricao: 'Acompanhe o faturamento da noite de qualquer lugar.', icone: '📱' },
              ],
            },
            'cafeterias': {
              titulo: 'Sistema Online para Cafeterias',
              subtitulo: 'Múltiplas filiais conectadas na nuvem',
              descricao: 'Gerencie uma ou mais cafeterias com dados centralizados. O Big Chef Desktop Online mantém tudo sincronizado entre filiais e terminais.',
              icone: '☕',
              beneficios: [
                { titulo: 'PDV sincronizado', descricao: 'Atendimento rápido no balcão com dados unificados entre filiais.', icone: '🏪' },
                { titulo: 'Programa de fidelidade', descricao: 'Clientes acumulam pontos em qualquer filial conectada.', icone: '⭐' },
                { titulo: 'Controle de insumos', descricao: 'Estoque sincronizado entre todas as unidades.', icone: '📊' },
                { titulo: 'Relatórios consolidados', descricao: 'Visualize resultados de todas as filiais em um só painel.', icone: '📈' },
              ],
            },
            'dark-kitchens': {
              titulo: 'Sistema Online para Dark Kitchens',
              subtitulo: 'Gestão de delivery com dados na nuvem',
              descricao: 'Gerencie múltiplas cozinhas e canais de delivery com dados sincronizados. O Big Chef Desktop Online centraliza pedidos de todos os marketplaces.',
              icone: '🏭',
              beneficios: [
                { titulo: 'Integração com iFood e AiqFome', descricao: 'Pedidos de todos os canais centralizados e sincronizados na nuvem.', icone: '🔗' },
                { titulo: 'Múltiplas cozinhas', descricao: 'Gerencie várias dark kitchens com dados unificados.', icone: '🏭' },
                { titulo: 'Painel de produção remoto', descricao: 'Acompanhe a produção de qualquer lugar conectado.', icone: '📋' },
                { titulo: 'Relatórios centralizados', descricao: 'Performance de todas as unidades em um só dashboard.', icone: '📊' },
              ],
            },
            'sistema-para-delivery': {
              titulo: 'Sistema Online para Delivery',
              subtitulo: 'Delivery profissional com dados na nuvem',
              descricao: 'Monte seu canal de delivery com cardápio digital e chatbot no WhatsApp. O Big Chef Desktop Online sincroniza pedidos em todos os terminais automaticamente.',
              icone: '🛵',
              beneficios: [
                { titulo: 'Site próprio de delivery', descricao: 'Cardápio online sincronizado automaticamente com o sistema.', icone: '🌐' },
                { titulo: 'Chatbot para WhatsApp', descricao: 'Pedidos automáticos pelo WhatsApp sincronizados na nuvem.', icone: '💬' },
                { titulo: 'Rastreamento de pedido', descricao: 'Status em tempo real para o cliente, atualizado de qualquer terminal.', icone: '📍' },
                { titulo: 'Gestão de entregadores', descricao: 'Controle rotas e atribuições de qualquer computador conectado.', icone: '🏍️' },
              ],
            },
          },
          parceiros: {
            seloPagina: 'Programa de Parceiros',
            tituloPagina: 'Cresça com o Big Chef Desktop Online',
            subtituloPagina: 'Seja um parceiro comercial e ganhe comissões recorrentes indicando o ERP com sincronização na nuvem e acesso multi-terminal.',
            seloSobre: 'Quem somos',
            tituloSobre: 'Conheça a Word System',
            descricaoSobre: 'Desenvolvemos soluções de gestão com sincronização na nuvem para restaurantes, bares e delivery há mais de uma década.',
            descricaoEmpresa: 'Especializada no desenvolvimento de ERPs com acesso remoto para o setor de alimentação fora do lar.',
            sede: 'Santa Fé — PR, Brasil',
            cnpjLabel: 'Empresa registrada e ativa desde 2016',
            atuacao: 'Todo o território nacional',
            numeros: [
              { valor: '+10', rotulo: 'Anos no mercado', icone: '📅' },
              { valor: '+3.000', rotulo: 'Clientes ativos', icone: '👥' },
              { valor: '+15.000', rotulo: 'Estabelecimentos gerenciados', icone: '🏪' },
              { valor: '24/7', rotulo: 'Suporte disponível', icone: '🎧' },
            ],
            motivosParceiro: [
              'Sistema com sincronização na nuvem — acesso de qualquer lugar',
              'Multi-terminal: ideal para restaurantes com vários caixas',
              'Mais de 3.000 clientes ativos em todo o Brasil',
              'Alta taxa de conversão e retenção de clientes',
              'Suporte completo com configuração remota inclusa',
              'Comissões recorrentes e previsíveis',
            ],
            vantagens: [
              { icone: '💰', titulo: 'Comissão Recorrente', descricao: 'Receba comissões mensais por cada cliente ativo indicado por você.' },
              { icone: '📦', titulo: 'Material de Apoio', descricao: 'Materiais de marketing focados nas vantagens da sincronização na nuvem.' },
              { icone: '🎓', titulo: 'Treinamento Especializado', descricao: 'Capacitação completa sobre o sistema com acesso remoto.' },
              { icone: '🤝', titulo: 'Suporte Dedicado', descricao: 'Canal direto com nosso time comercial para fechar negócios.' },
              { icone: '📈', titulo: 'Painel do Parceiro', descricao: 'Acompanhe indicações, comissões e desempenho em tempo real.' },
              { icone: '🚀', titulo: 'Sem Investimento Inicial', descricao: 'Torne-se parceiro sem nenhum custo. Cadastre-se e comece.' },
            ],
            comoFunciona: [
              { passo: '1', titulo: 'Cadastre-se', descricao: 'Preencha o formulário com seus dados e aguarde a aprovação.' },
              { passo: '2', titulo: 'Receba seu acesso', descricao: 'Após aprovado, você terá acesso ao painel e materiais de apoio.' },
              { passo: '3', titulo: 'Indique clientes', descricao: 'Compartilhe seu link exclusivo e apresente o Big Chef Desktop Online.' },
              { passo: '4', titulo: 'Receba comissões', descricao: 'A cada cliente que assinar, você recebe comissão recorrente.' },
            ],
            itensLateral: [
              'Comissão **recorrente** mensal',
              'Material de marketing **exclusivo**',
              'Treinamento **completo** sobre o produto online',
              'Suporte **dedicado** do time comercial',
              'Painel para acompanhar **indicações e ganhos**',
              '**Sem investimento** inicial',
            ],
            perfisIdeais: ['Consultores de TI', 'Contadores', 'Vendedores autônomos', 'Empresas de tecnologia', 'Revendedores de software'],
          },
        },
      },

      // Web → textos focados em acessar pelo navegador
      'web': {
        nome: 'Big Chef Web',
        slogan: 'Seu restaurante direto no navegador',
        descricao: 'Acesse o Big Chef pelo navegador, sem instalar nada. Ideal para quem quer praticidade total.',
        menus: {
          funcionalidades: {
            rotulo: "Funcionalidades",
            prefixoRota: "/funcionalidades",
            itens: [
              { rotulo: "Frente de Caixa (PDV)", slug: "frente-de-caixa-pdv" },
              // { rotulo: "Chatbot para Delivery", slug: "chatbot-para-delivery" },
              { rotulo: "Financeiro", slug: "financeiro" },
              { rotulo: "Relatórios Gerenciais", slug: "relatorios-gerenciais" },
            ],
          },
          segmentos: {
            rotulo: "Segmentos",
            prefixoRota: "/segmentos",
            itens: [
              { rotulo: "Restaurantes", slug: "restaurantes" },
              { rotulo: "Sistema para Delivery", slug: "sistema-para-delivery" },
            ],
          },
        },
        textos: {
          heroi: {
            selo: 'Zero instalação — 100% no navegador',
            tituloAntes: 'Seu restaurante no',
            tituloDestaque: 'navegador',
            subtitulo: 'Com o Big Chef Web você acessa o sistema completo direto pelo Chrome, Edge ou Safari. Sem downloads, sem atualizações manuais — sempre na última versão.',
            ctaPrimario: 'Começar {trialDays} dias grátis',
            ctaSecundario: 'Acessar sistema web',
          },
          appGarcom: {
            selo: 'Aplicativo Nativo',
            titulo: 'Garçom anota no celular, a cozinha',
            tituloDestaque: 'já visualiza.',
            subtitulo: 'O app do garçom se conecta diretamente ao Big Chef Web pela internet. Pedidos chegam na cozinha instantaneamente, sem precisar de servidor local.',
            recursos: [
              { titulo: 'Conexão direta pela nuvem', descricao: 'O app envia pedidos direto para o painel web — sem precisar de servidor ou rede local.' },
              { titulo: 'Fechamento pelo navegador', descricao: 'O caixa acompanha e fecha as mesas pelo navegador, com os pedidos do app já integrados.' },
            ],
          },
          funcionalidades: {
            titulo: 'Tudo pelo navegador, sem instalar nada',
            subtitulo: 'Acesse de qualquer dispositivo com internet — computador, tablet ou celular.',
            cartoes: [
              { icone: '🌐', titulo: 'Acesso Universal', descricao: 'Funciona em qualquer dispositivo com navegador moderno: PC, Mac, Chromebook, tablet.' },
              { icone: '🔒', titulo: 'Segurança na Nuvem', descricao: 'Seus dados são criptografados e armazenados com backups automáticos diários.' },
              { icone: '⚡', titulo: 'Sempre Atualizado', descricao: 'Novas funcionalidades e correções chegam automaticamente, sem precisar baixar nada.' },
              { icone: '🏪', titulo: 'PDV no Navegador', descricao: 'Frente de caixa completa rodando direto no browser, com suporte a impressoras térmicas.' },
              { icone: '📱', titulo: 'Responsivo', descricao: 'Interface que se adapta ao tamanho da tela — use no notebook, monitor ou tablet.' },
              { icone: '📊', titulo: 'Dashboards Online', descricao: 'Acompanhe seus indicadores de qualquer lugar, a qualquer hora.' },
            ],
          },
          estatisticas: {
            selo: 'Resultados reais',
            titulo: 'Quem usa o Big Chef Web já comprovou',
            itens: [
              { valor: '3.200+', rotulo: 'Restaurantes ativos', icone: '🏪' },
              { valor: '98%', rotulo: 'Taxa de satisfação', icone: '⭐' },
              { valor: '40%', rotulo: 'Redução de erros', icone: '📉' },
              { valor: '10 anos', rotulo: 'No mercado', icone: '🏆' },
            ],
            depoimentos: [
              {
                citacao: 'Abri o navegador, entrei no sistema e já comecei a vender. Não precisei instalar nada, nem chamar técnico. Incrível.',
                nome: 'Marcos Aurélio',
                papel: 'Dono — Churrascaria do Marcos, SP',
                iniciais: 'MA',
              },
              {
                citacao: 'Uso o Big Chef Web no tablet do caixa e no notebook de casa. Tudo sempre sincronizado e sem complicação.',
                nome: 'Sabrina Fonseca',
                papel: 'Gerente — Bistrô da Villa, RJ',
                iniciais: 'SF',
              },
              {
                citacao: 'A versão web é leve e rápida. Mesmo no Chromebook baratinho da loja, o sistema roda perfeitamente.',
                nome: 'Rafael Teixeira',
                papel: 'Sócio — Pizza da Hora, BH',
                iniciais: 'RT',
              },
            ],
          },
          suporte: {
            selo: 'Suporte humanizado',
            titulo: 'Ajuda rápida, direto no navegador',
            subtitulo: 'Nosso time resolve tudo remotamente — sem precisar instalar programa de acesso remoto. Basta compartilhar a tela pelo navegador.',
            cartoes: [
              {
                icone: '📞',
                titulo: 'Suporte por WhatsApp',
                descricao: 'Fale com um especialista via WhatsApp e receba orientação passo a passo para resolver no navegador.',
              },
              {
                icone: '💻',
                titulo: 'Suporte pelo Navegador',
                descricao: 'Compartilhe sua tela direto pelo browser e nosso time resolve o problema em tempo real — sem instalar nada.',
                destaque: true,
                rotuloDestaque: 'sem instalação',
              },
              {
                icone: '🎓',
                titulo: 'Treinamento Online',
                descricao: 'Onboarding por videochamada para você e sua equipe dominarem o sistema web desde o primeiro acesso.',
              },
            ],
            tituloHorario: 'Horário de atendimento',
            rotuloDomingo: 'Domingo e feriados',
            valorDomingo: 'Plantão',
            notaDomingo: 'Urgências via WhatsApp',
            notaSuporteCompleto: 'Suporte completo',
          },
          contato: {
            selo: 'Fale com a gente',
            titulo: 'Quer experimentar o Big Chef Web?',
            subtitulo: 'Tem dúvidas sobre compatibilidade, impressoras térmicas ou como funciona no navegador? Nossa equipe mostra tudo ao vivo.',
            rotuloWhatsapp: 'WhatsApp Comercial',
            notaWhatsapp: 'Resposta em minutos no horário de atendimento',
            rotuloEmail: 'E-mail',
            textoBotaoFormulario: 'Enviar mensagem via WhatsApp',
            notaFormulario: 'Ao enviar, você será redirecionado ao WhatsApp com os dados preenchidos.',
          },
          chamadaFinal: {
            selo: 'Sem download necessário',
            titulo: 'Comece agora mesmo, direto no navegador',
            subtitulo: 'Teste o Big Chef Web por {trialDays} dias grátis. Basta criar a conta e acessar — sem instalar nada.',
            ctaPrimario: 'Criar conta grátis',
            ctaSecundario: 'Ver planos e preços',
          },
          cadastro: {
            seloTeste: 'dias grátis · sem cartão',
            tituloFormulario: 'Crie sua conta no Big Chef Web',
            subtituloFormulario: 'Preencha os dados e acesse o sistema pelo navegador, sem instalar nada.',
            campoEstabelecimento: 'Nome do estabelecimento',
            placeholderCampoEstabelecimento: 'Ex: Restaurante da Família',
            seloRiscoLateral: 'Sem risco',
            tituloLateral: 'Zero instalação, 100% online!',
            itensLateral: [
              'Sem precisar cadastrar cartão de crédito',
              'Acesso a **todos os módulos** durante o teste',
              'Funciona em **qualquer navegador** moderno',
              'Sempre na **última versão** automaticamente',
              'Cancele quando quiser, sem burocracia',
            ],
            rotuloModulosLateral: 'Módulos inclusos no teste:',
            modulosLateral: ['PDV Rápido', 'Delivery', 'NFC-e / NF-e', 'Financeiro', 'App Garçom', 'Relatórios'],
          },
          download: {
            tituloSecao: 'Acessar o Big Chef Web',
            prefixoOsDetectado: 'Detectamos que você usa',
            osDesconhecido: 'Escolha como acessar abaixo',
            prefixoBotaoDownload: 'Acessar via',
            botaoOutrasPlataformas: 'Outras formas de acesso',
            tituloPassos: 'Como começar em 3 passos',
            passos: [
              { titulo: 'Crie sua conta', descricao: 'Preencha o formulário de cadastro. Leva menos de 1 minuto.' },
              { titulo: 'Acesse pelo navegador', descricao: 'Abra o Chrome, Edge ou Safari e faça login no sistema.' },
              { titulo: 'Configure e comece a vender', descricao: 'Cadastre produtos, configure seu restaurante e comece a operar.' },
            ],
            tituloRequisitos: 'Requisitos do sistema',
            rotuloDesktop: 'Navegador (PDV / Painel)',
            rotuloMobile: 'Celular (App Garçom / Delivery)',
          },
          planos: {
            seloHeroi: 'dias grátis, sem cartão de crédito',
            tituloHeroi: 'Big Chef Web: seu restaurante direto no navegador',
            subtituloHeroi: 'Experimente por {trialDays} dias grátis, sem cartão de crédito. Acesse pelo navegador, sem instalar nada, com todos os módulos liberados!',
            botaoEscolher: 'Comece Agora',
            botaoPlanoAtual: 'Plano Atual',
            rotuloMaisVendido: 'Mais vendido',
            linkCompararPlanos: 'Comparar os Planos',
            prefixoEconomize: 'Economize',
            sufixoMes: '/mês',
            sufixoTotal: '/total',
            rotuloUsuarios: 'Usuários',
            rotuloPainelAdmin: 'Painel Administrativo',
            rotuloAppMobile: 'App Android e iOS',
            rotuloEspacoIlimitado: 'Espaço ilimitado',
            seloComparativo: 'Comparativo',
            tituloComparativo: 'Compare os planos e encontre a solução ideal para operar pelo navegador',
            dicaRolarMobile: 'Role para comparar os planos',
            botaoComecePelaTabela: 'Comece grátis',
          },
          paginasFuncionalidades: {
            'frente-de-caixa-pdv': {
              titulo: 'Frente de Caixa (PDV) — Web',
              subtitulo: 'PDV completo direto no navegador',
              descricao: 'O PDV do Big Chef Web funciona direto no navegador, sem instalar nada. Abra o Chrome ou Edge e comece a vender — ideal para operações ágeis e sem burocracia.',
              icone: '🏪',
              recursos: [
                { titulo: 'Zero instalação', descricao: 'Abra o navegador e comece a vender imediatamente.', icone: '🌐' },
                { titulo: 'Sempre atualizado', descricao: 'Novas funcionalidades disponíveis automaticamente, sem baixar nada.', icone: '🔄' },
                { titulo: 'Múltiplas formas de pagamento', descricao: 'Dinheiro, cartão, Pix e vouchers em uma única venda.', icone: '💳' },
                { titulo: 'Acesso de qualquer dispositivo', descricao: 'Funciona em qualquer computador ou tablet com navegador.', icone: '📱' },
              ],
            },
            // 'chatbot-para-delivery': {
            //   titulo: 'Chatbot para Delivery — Web',
            //   subtitulo: 'Delivery completo gerenciado pelo navegador',
            //   descricao: 'Receba pedidos pelo WhatsApp e site próprio e gerencie tudo pelo navegador. Sem instalar software, sem complicação — só abrir e operar.',
            //   icone: '🛵',
            //   recursos: [
            //     { titulo: 'Cardápio digital', descricao: 'Seu cardápio online sempre atualizado, editável de qualquer navegador.', icone: '📱' },
            //     { titulo: 'Chatbot WhatsApp', descricao: 'Atendimento automático 24h pelo WhatsApp do restaurante.', icone: '🤖' },
            //     { titulo: 'Acompanhamento de pedido', descricao: 'Monitore todos os pedidos em tempo real pelo navegador.', icone: '📍' },
            //     { titulo: 'Integração com iFood e AiqFome', descricao: 'Pedidos de marketplaces direto no painel web.', icone: '🔗' },
            //   ],
            // },
            'financeiro': {
              titulo: 'Financeiro — Web',
              subtitulo: 'Gestão financeira acessível de qualquer navegador',
              descricao: 'Controle receitas, despesas e fluxo de caixa pelo navegador, de qualquer lugar. Sem instalar nada — basta abrir e gerenciar suas finanças.',
              icone: '💰',
              recursos: [
                { titulo: 'Fluxo de caixa online', descricao: 'Entradas e saídas atualizadas em tempo real no navegador.', icone: '📊' },
                { titulo: 'Contas a pagar e receber', descricao: 'Gerencie vencimentos de qualquer lugar com acesso web.', icone: '📅' },
                { titulo: 'Conciliação bancária', descricao: 'Compare lançamentos com o extrato bancário pelo navegador.', icone: '🏦' },
                { titulo: 'DRE automático', descricao: 'Demonstrativo de resultados gerado e acessível online.', icone: '📈' },
              ],
            },
            'relatorios-gerenciais': {
              titulo: 'Relatórios Gerenciais — Web',
              subtitulo: 'Dados estratégicos acessíveis de qualquer navegador',
              descricao: 'Dashboards e relatórios detalhados acessíveis pelo navegador. Ticket médio, produtos mais vendidos e DRE — sempre atualizados, sem instalar nada.',
              icone: '📊',
              recursos: [
                { titulo: 'Dashboard online', descricao: 'Indicadores do dia acessíveis de qualquer navegador.', icone: '📈' },
                { titulo: 'Ticket médio', descricao: 'Acompanhe o valor médio das vendas de qualquer dispositivo.', icone: '🎫' },
                { titulo: 'Ranking de produtos', descricao: 'Saiba quais itens mais vendem em tempo real pelo navegador.', icone: '🏆' },
                { titulo: 'Relatório por garçom', descricao: 'Meça a performance de cada atendente de qualquer lugar.', icone: '👤' },
              ],
            },
          },
          paginasSegmentos: {
            'restaurantes': {
              titulo: 'Sistema Web para Restaurantes',
              subtitulo: 'Seu restaurante no navegador, sem instalar nada',
              descricao: 'Acesse o Big Chef Web pelo navegador e gerencie seu restaurante de qualquer dispositivo. Sempre atualizado, sem downloads, sem complicação.',
              icone: '🍽️',
              beneficios: [
                { titulo: 'Zero instalação', descricao: 'Abra o navegador e comece a operar imediatamente.', icone: '🌐' },
                { titulo: 'Sempre atualizado', descricao: 'Novas funcionalidades disponíveis automaticamente.', icone: '🔄' },
                { titulo: 'Acesso de qualquer dispositivo', descricao: 'Funciona no computador, tablet ou celular com navegador.', icone: '📱' },
                { titulo: 'Gestão financeira completa', descricao: 'Fluxo de caixa, DRE e relatórios acessíveis online.', icone: '💰' },
              ],
            },
            'sistema-para-delivery': {
              titulo: 'Sistema Web para Delivery',
              subtitulo: 'Delivery profissional direto no navegador',
              descricao: 'Monte seu canal de delivery com cardápio digital e chatbot no WhatsApp. Gerencie tudo pelo navegador, sem instalar nenhum software.',
              icone: '🛵',
              beneficios: [
                { titulo: 'Cardápio digital online', descricao: 'Seu cardápio sempre atualizado e editável pelo navegador.', icone: '🌐' },
                { titulo: 'Chatbot para WhatsApp', descricao: 'Pedidos automáticos pelo WhatsApp gerenciados no navegador.', icone: '💬' },
                { titulo: 'Rastreamento de pedido', descricao: 'Status em tempo real para o cliente.', icone: '📍' },
                { titulo: 'Sem instalação', descricao: 'Gerencie todo o delivery pelo navegador, de qualquer lugar.', icone: '🚀' },
              ],
            },
          },
          parceiros: {
            seloPagina: 'Programa de Parceiros',
            tituloPagina: 'Cresça com o Big Chef Web',
            subtituloPagina: 'Seja um parceiro comercial e ganhe comissões recorrentes indicando o ERP que funciona direto no navegador, sem instalação.',
            seloSobre: 'Quem somos',
            tituloSobre: 'Conheça a Word System',
            descricaoSobre: 'Desenvolvemos soluções de gestão acessíveis pelo navegador para restaurantes, bares e delivery há mais de uma década.',
            descricaoEmpresa: 'Especializada no desenvolvimento de ERPs web para o setor de alimentação fora do lar.',
            sede: 'Santa Fé — PR, Brasil',
            cnpjLabel: 'Empresa registrada e ativa desde 2016',
            atuacao: 'Todo o território nacional',
            numeros: [
              { valor: '+10', rotulo: 'Anos no mercado', icone: '📅' },
              { valor: '+3.000', rotulo: 'Clientes ativos', icone: '👥' },
              { valor: '+15.000', rotulo: 'Estabelecimentos gerenciados', icone: '🏪' },
              { valor: '24/7', rotulo: 'Suporte disponível', icone: '🎧' },
            ],
            motivosParceiro: [
              'Sistema 100% web — funciona em qualquer navegador',
              'Zero instalação: o cliente acessa e já começa a usar',
              'Mais de 3.000 clientes ativos em todo o Brasil',
              'Alta taxa de conversão pela facilidade de acesso',
              'Suporte completo sem necessidade de visita técnica',
              'Comissões recorrentes e previsíveis',
            ],
            vantagens: [
              { icone: '💰', titulo: 'Comissão Recorrente', descricao: 'Receba comissões mensais por cada cliente ativo indicado por você.' },
              { icone: '📦', titulo: 'Material de Apoio', descricao: 'Materiais de marketing focados na praticidade do acesso web.' },
              { icone: '🎓', titulo: 'Treinamento Especializado', descricao: 'Capacitação completa sobre o sistema web para vender com confiança.' },
              { icone: '🤝', titulo: 'Suporte Dedicado', descricao: 'Canal direto com nosso time comercial para fechar negócios.' },
              { icone: '📈', titulo: 'Painel do Parceiro', descricao: 'Acompanhe indicações, comissões e desempenho em tempo real.' },
              { icone: '🚀', titulo: 'Sem Investimento Inicial', descricao: 'Torne-se parceiro sem nenhum custo. Cadastre-se e comece.' },
            ],
            comoFunciona: [
              { passo: '1', titulo: 'Cadastre-se', descricao: 'Preencha o formulário com seus dados e aguarde a aprovação.' },
              { passo: '2', titulo: 'Receba seu acesso', descricao: 'Após aprovado, você terá acesso ao painel e materiais de apoio.' },
              { passo: '3', titulo: 'Indique clientes', descricao: 'Compartilhe seu link exclusivo e apresente o Big Chef Web.' },
              { passo: '4', titulo: 'Receba comissões', descricao: 'A cada cliente que assinar, você recebe comissão recorrente.' },
            ],
            itensLateral: [
              'Comissão **recorrente** mensal',
              'Material de marketing **exclusivo**',
              'Treinamento **completo** sobre o produto web',
              'Suporte **dedicado** do time comercial',
              'Painel para acompanhar **indicações e ganhos**',
              '**Sem investimento** inicial',
            ],
            perfisIdeais: ['Consultores de TI', 'Contadores', 'Vendedores autônomos', 'Empresas de tecnologia', 'Revendedores de software'],
          },
        },
      },
    },

    menus: {
      funcionalidades: {
        rotulo: "Funcionalidades",
        prefixoRota: "/funcionalidades",
        itens: [
          { rotulo: "Frente de Caixa (PDV)", slug: "frente-de-caixa-pdv" },
          { rotulo: "Mesas e Comandas", slug: "mesas-e-comandas" },
          // { rotulo: "Chatbot para Delivery", slug: "chatbot-para-delivery" },
          { rotulo: "Financeiro", slug: "financeiro" },
          { rotulo: "Emissão Fiscal", slug: "emissao-fiscal" },
          { rotulo: "Relatórios Gerenciais", slug: "relatorios-gerenciais" },
        ],
      },
      segmentos: {
        rotulo: "Segmentos",
        prefixoRota: "/segmentos",
        itens: [
          { rotulo: "Restaurantes", slug: "restaurantes" },
          { rotulo: "Bares e Baladas", slug: "bares-e-baladas" },
          { rotulo: "Sistema para Delivery", slug: "sistema-para-delivery" },
        ],
      },
      plataformas: {
        rotulo: "Plataformas",
        prefixoRota: "/plataformas",
        itens: [
          { rotulo: "Desktop Local", slug: "desktop-local" },
          { rotulo: "Desktop Online", slug: "desktop-online" },
          { rotulo: "Web", slug: "web" },
        ],
      },
    },

    contato: {
      urlWhatsapp: "https://wa.me/5500000000000",
      email: "contato@bigchef.com.br",
    },

    suporte: {
      horarios: {
        diasUteis: "07:30h – 17:30h",
        sabado: "09h – 12h",
      },
    },

    links: {
      sistemaWeb: "https://bigchef.com.br/painel/#/autenticacao/login",
      appStore: URL_APP_STORE,
      playStore: URL_PLAY_STORE,
    },

    download: {
      categorias: [
        { chave: "sistema_desktop", rotulo: "Sistema Desktop", descricao: "Desktop (PDV / Painel)" },
        { chave: "sistema_web", rotulo: "Sistema Web", descricao: "Web (PDV / Painel)" },
        { chave: "app_garcom", rotulo: "App do Garçom", descricao: "Android / iPhone" },
      ],
      itens: [
        {
          id: "sistema_desktop-windows",
          chavePlataforma: "windows",
          chaveCategoria: "sistema_desktop",
          rotulo: "Windows",
          versao: "Windows 10 / 11 (64-bit)",
          tamanho: "142 MB",
          urlDownload: "/baixar?destino=desktop-local",
          corBadge: "#0078D4",
        },
        {
          id: "sistema_web-windows",
          chavePlataforma: "windows",
          chaveCategoria: "sistema_web",
          rotulo: "Windows",
          versao: "Windows 10 / 11 (64-bit)",
          tamanho: "142 MB",
          urlDownload: "/baixar?destino=desktop-online",
          corBadge: "#0078D4",
        },
        {
          id: "app-garcom-android",
          chavePlataforma: "android",
          chaveCategoria: "app_garcom",
          rotulo: "Android",
          versao: "Android 8.0 ou superior",
          tamanho: "48 MB",
          urlDownload: URL_PLAY_STORE,
          corBadge: "#34A853",
        },
        {
          id: "app-garcom-ios",
          chavePlataforma: "ios",
          chaveCategoria: "app_garcom",
          rotulo: "iPhone / iPad",
          versao: "iOS 15 ou superior",
          tamanho: "62 MB",
          urlDownload: URL_APP_STORE,
          corBadge: "#000000",
        },
      ],
      requisitos: {
        desktop: [
          { rotulo: "Sistema operacional", minimo: "Windows 10 / macOS 12 / Ubuntu 20.04", recomendado: "Windows 11 / macOS 14 / Ubuntu 22.04" },
          { rotulo: "Processador", minimo: "Intel i3 / AMD Ryzen 3", recomendado: "Intel i5 / AMD Ryzen 5 ou superior" },
          { rotulo: "Memória RAM", minimo: "4 GB", recomendado: "8 GB ou mais" },
          { rotulo: "Armazenamento", minimo: "5 GB livres", recomendado: "20 GB livres (SSD)" },
          { rotulo: "Conexão", minimo: "2 Mbps (só login e sync)", recomendado: "10 Mbps ou mais" },
        ],
        celular: [
          { rotulo: "Sistema operacional", minimo: "Android 8.0 / iOS 15", recomendado: "Android 12+ / iOS 17+" },
          { rotulo: "Processador", minimo: "Quad-core 1.6 GHz", recomendado: "Octa-core 2.0 GHz ou superior" },
          { rotulo: "Memória RAM", minimo: "2 GB", recomendado: "4 GB ou mais" },
          { rotulo: "Armazenamento", minimo: "200 MB livres", recomendado: "1 GB livres" },
          { rotulo: "Conexão", minimo: "Wi-Fi 2.4 GHz / 4G", recomendado: "Wi-Fi 5 GHz / 4G+ ou 5G" },
        ],
      },
    },
  },

  // ┌──────────────────────────────────────────────────────────────────────────┐
  // │  TEXTOS                                                                 │
  // └──────────────────────────────────────────────────────────────────────────┘
  textos: {
    // ── Página Inicial ─────────────────────────────────────────────────────
    heroi: {
      selo: "A plataforma mais completa para o seu restaurante",
      tituloAntes: "Automatize seu restaurante e venda",
      tituloDestaque: "muito mais rápido",
      subtitulo: "Reduza erros, acelere o atendimento das mesas e tenha controle total do seu delivery no Big Chef.",
      ctaPrimario: "Começar {trialDays} dias grátis",
      ctaSecundario: "Ver sistema funcionando",
    },
    appGarcom: {
      selo: "Aplicativo Nativo",
      titulo: "O garçom anota, a cozinha",
      tituloDestaque: "já prepara.",
      subtitulo: "Transforme smartphones em terminais de pontos de venda. Reduza o tempo de espera dos clientes e elimine as comandas de papel.",
      recursos: [
        { titulo: "Pedidos instantâneos", descricao: "Impressão direta nos monitores ou impressoras da cozinha e bar, sem atrasos." },
        { titulo: "Fechamento Rápido", descricao: "Divida a conta facilmente e acompanhe gorjetas no próprio celular do garçom." },
      ],
    },
    funcionalidades: {
      titulo: "Tudo integrado para o seu negócio voar",
      subtitulo: "Nós unimos PDV, mesas e delivery de um jeito que você nunca viu igual.",
      cartoes: [
        { icone: "🏪", titulo: "Vendas de PDV e Balcão", descricao: "Operação super rápida no balcão para não gerar filas, com leitura de balanças e códigos de barras." },
        { icone: "🧾", titulo: "Mesas e Comandas", descricao: "Controle detalhado do salão com comandas individuais e divisão de contas ágil." },
        { icone: "🛵", titulo: "Delivery e Site Próprio", descricao: "Receba pedidos no seu próprio site de delivery sem pagar taxas extras abusivas." },
        { icone: "💰", titulo: "Financeiro Completo", descricao: "Gestão de movimentações, Controle de Contas a Receber e Contas a Pagar em um clique." },
        { icone: "📑", titulo: "Emissão Fiscal (NFC-e / NF-e)", descricao: "Geração de nota fiscal de consumidor e nota fiscal eletrônica totalmente integrada e rápida." },
        { icone: "📊", titulo: "Dashboards Poderosos", descricao: "Seu ticket médio, DRE e pratos mais vendidos desenhados na sua tela diariamente com relatórios." },
      ],
    },
    estatisticas: {
      selo: "Resultados reais",
      titulo: "Números que falam por si",
      itens: [
        { valor: "3.200+", rotulo: "Restaurantes ativos", icone: "🏪" },
        { valor: "98%", rotulo: "Taxa de satisfação", icone: "⭐" },
        { valor: "40%", rotulo: "Redução de erros", icone: "📉" },
        { valor: "10 anos", rotulo: "No mercado", icone: "🏆" },
      ],
      depoimentos: [
        {
          citacao: "Antes eu perdia pedido toda sexta à noite. Com o Big Chef, a cozinha já recebe tudo na hora e o caixa fecha sozinho.",
          nome: "Marcos Aurélio",
          papel: "Dono — Churrascaria do Marcos, SP",
          iniciais: "MA",
        },
        {
          citacao: "A emissão de NFC-e integrada economizou horas do meu contador. Recomendo para qualquer restaurante que queira crescer.",
          nome: "Sabrina Fonseca",
          papel: "Gerente — Bistrô da Villa, RJ",
          iniciais: "SF",
        },
        {
          citacao: "Passamos de 80 para 130 pedidos de delivery por dia sem contratar mais ninguém. O sistema absorveu todo o volume.",
          nome: "Rafael Teixeira",
          papel: "Sócio — Pizza da Hora, BH",
          iniciais: "RT",
        },
      ],
    },
    suporte: {
      selo: "Suporte humanizado",
      titulo: "Você nunca fica sozinho",
      subtitulo: "Nossa equipe está disponível para tirar dúvidas, resolver problemas e garantir que seu restaurante nunca pare.",
      cartoes: [
        {
          icone: "📞",
          titulo: "Suporte por WhatsApp",
          descricao: "Fale com um especialista via WhatsApp sem burocracia e receba respostas rápidas no seu celular.",
        },
        {
          icone: "💻",
          titulo: "Acesso Remoto",
          descricao: "Nosso time acessa seu computador remotamente para resolver qualquer problema na hora, sem você precisar descrever nada.",
          destaque: true,
          rotuloDestaque: "exclusivo",
        },
        {
          icone: "🎓",
          titulo: "Treinamento Incluso",
          descricao: "Onboarding completo com a equipe de implantação para você e sua equipe dominarem o sistema desde o dia 1.",
        },
      ],
      tituloHorario: "Horário de atendimento",
      rotuloDomingo: "Domingo e feriados",
      valorDomingo: "Plantão",
      notaDomingo: "Urgências via WhatsApp",
      notaSuporteCompleto: "Suporte completo",
    },
    contato: {
      selo: "Fale com a gente",
      titulo: "Precisa de algo diferente?",
      subtitulo:
        "Tem uma rede de restaurantes, uma operação fora do padrão ou quer ver o sistema funcionando antes de decidir? Nossa equipe está pronta para entender o seu cenário e mostrar a melhor solução.",
      rotuloWhatsapp: "WhatsApp Comercial",
      notaWhatsapp: "Resposta em minutos no horário de atendimento",
      rotuloEmail: "E-mail",
      textoBotaoFormulario: "Enviar mensagem via WhatsApp",
      notaFormulario: "Ao enviar, você será redirecionado ao WhatsApp com os dados preenchidos.",
    },
    chamadaFinal: {
      selo: "Sem cartão de crédito",
      titulo: "Pronto para transformar seu restaurante?",
      subtitulo: "Teste o Big Chef por {trialDays} dias com todos os módulos ativados, sem compromisso e sem pagar nada.",
      ctaPrimario: "Começar {trialDays} dias grátis",
      ctaSecundario: "Ver planos e preços",
    },

    // ── Cadastro ─────────────────────────────────────────────────────────────
    cadastro: {
      seloTeste: "dias grátis · sem cartão",
      tituloFormulario: "Crie sua conta no Big Chef",
      subtituloFormulario: "Preencha os dados abaixo para começar agora mesmo.",
      campoEstabelecimento: "Nome do estabelecimento",
      placeholderCampoEstabelecimento: "Ex: Restaurante da Família",
      seloRiscoLateral: "Sem risco",
      tituloLateral: "Sua gestão pode ser simples como um click!",
      itensLateral: [
        "Sem precisar cadastrar cartão de crédito",
        "Acesso a **todos os módulos** durante o teste",
        "PDV, Mesas, Comandas, Delivery e NFC-e liberados",
        "Suporte humano durante seu período de teste",
        "Cancele quando quiser, sem burocracia",
      ],
      rotuloModulosLateral: "Módulos inclusos no teste:",
      modulosLateral: ["PDV Rápido", "Mesas", "Delivery", "Comandas", "NFC-e / NF-e", "Financeiro", "App Garçom", "Relatórios"],
    },

    // ── Baixar / Download ────────────────────────────────────────────────────
    baixar: {
      tituloSucesso: "Cadastro realizado!",
      subtituloSucesso: "Sua conta foi criada com sucesso. Agora baixe o sistema para começar a usar.",
      rotuloAcessoWeb: "Ou acesse pelo navegador em",
    },
    download: {
      tituloSecao: "Baixar o Big Chef",
      prefixoOsDetectado: "Detectamos que você usa",
      osDesconhecido: "Escolha sua plataforma abaixo",
      prefixoBotaoDownload: "Baixar para",
      botaoOutrasPlataformas: "Baixar para outra plataforma",
      tituloPassos: "Como começar em 3 passos",
      passos: [
        { titulo: "Baixe e instale", descricao: "Clique no botão acima, baixe o instalador e execute. A instalação leva menos de 2 minutos." },
        { titulo: "Faça login", descricao: "Abra o sistema e entre com o e-mail e senha que acabou de cadastrar. Seus módulos já estão liberados." },
        { titulo: "Configure seu restaurante", descricao: "Siga o assistente de configuração inicial: adicione seus produtos, mesas e comece a vender." },
      ],
      tituloRequisitos: "Requisitos do sistema",
      rotuloDesktop: "Computador (PDV / Painel)",
      rotuloMobile: "Celular (App Garçom / Delivery)",
    },

    // ── Planos ───────────────────────────────────────────────────────────────
    planos: {
      seloHeroi: "dias grátis, sem cartão de crédito",
      tituloHeroi: "ERP Big Chef: encontre o plano ideal para o seu negócio",
      subtituloHeroi: "Comece gratuitamente por {trialDays} dias, sem cadastro de cartão de crédito, e tenha acesso a todos os módulos do sistema!",
      botaoEscolher: "Comece Agora",
      botaoPlanoAtual: "Plano Atual",
      rotuloMaisVendido: "Mais vendido",
      linkCompararPlanos: "Comparar os Planos",
      prefixoEconomize: "Economize",
      sufixoMes: "/mês",
      sufixoTotal: "/total",
      rotuloUsuarios: "Usuários",
      rotuloPainelAdmin: "Painel Administrativo",
      rotuloAppMobile: "App Android e iOS",
      rotuloEspacoIlimitado: "Espaço ilimitado",
      seloComparativo: "Comparativo",
      tituloComparativo: "Compare nossos planos e descubra a solução certa para sua empresa",
      dicaRolarMobile: "Role para comparar os planos",
      botaoComecePelaTabela: "Comece grátis",
    },

    // ── Páginas de Funcionalidades ──────────────────────────────────────────
    paginasFuncionalidades: {
      "frente-de-caixa-pdv": {
        titulo: "Frente de Caixa (PDV)",
        subtitulo: "Atendimento rápido no balcão e no caixa",
        descricao: "O PDV do Big Chef foi pensado para operações de alta velocidade. Leitura de código de barras, balanças integradas e fechamento de venda em segundos.",
        icone: "🏪",
        recursos: [
          { titulo: "Leitura de código de barras", descricao: "Escaneie produtos para agilizar o atendimento no balcão.", icone: "📷" },
          { titulo: "Integração com balanças", descricao: "Peso automático direto no sistema, sem digitação manual.", icone: "⚖️" },
          { titulo: "Múltiplas formas de pagamento", descricao: "Aceite dinheiro, cartão, Pix e vouchers em uma única venda.", icone: "💳" },
          { titulo: "Modo offline", descricao: "Continue vendendo mesmo sem internet — sincroniza depois.", icone: "📶" },
        ],
      },
      "mesas-e-comandas": {
        titulo: "Mesas e Comandas",
        subtitulo: "Controle total do salão do seu restaurante",
        descricao: "Gerencie mesas, comandas individuais e divisão de contas com facilidade. Perfeito para restaurantes, bares e lanchonetes com atendimento no salão.",
        icone: "🧾",
        recursos: [
          { titulo: "Mapa de mesas visual", descricao: "Veja o status de cada mesa em tempo real.", icone: "🗺️" },
          { titulo: "Comandas individuais", descricao: "Cada cliente com sua comanda, sem confusão na hora de fechar.", icone: "📝" },
          { titulo: "Divisão de conta", descricao: "Divida por igual ou por consumo individual.", icone: "➗" },
          { titulo: "Transferência de mesa", descricao: "Troque clientes de mesa sem perder pedidos.", icone: "🔄" },
        ],
      },
      // "chatbot-para-delivery": {
      //   titulo: "Chatbot para Delivery",
      //   subtitulo: "Automatize pedidos pelo WhatsApp e site próprio",
      //   descricao: "Receba pedidos automaticamente pelo seu próprio canal de delivery, sem pagar comissões abusivas para marketplaces. Integração direta com WhatsApp.",
      //   icone: "🛵",
      //   recursos: [
      //     { titulo: "Cardápio digital", descricao: "Seu cardápio online sempre atualizado, sem taxa por pedido.", icone: "📱" },
      //     { titulo: "Chatbot WhatsApp", descricao: "Atendimento automático 24h pelo WhatsApp do restaurante.", icone: "🤖" },
      //     { titulo: "Acompanhamento de pedido", descricao: "Cliente acompanha o status do pedido em tempo real.", icone: "📍" },
      //     { titulo: "Integração com iFood e AiqFome", descricao: "Receba pedidos de marketplaces direto no seu sistema.", icone: "🔗" },
      //   ],
      // },
      "financeiro": {
        titulo: "Financeiro",
        subtitulo: "Gestão financeira completa e simplificada",
        descricao: "Controle receitas, despesas, contas a pagar e a receber em um só lugar. Tenha visão clara do fluxo de caixa do seu restaurante.",
        icone: "💰",
        recursos: [
          { titulo: "Fluxo de caixa", descricao: "Acompanhe entradas e saídas em tempo real.", icone: "📊" },
          { titulo: "Contas a pagar e receber", descricao: "Organize vencimentos e evite inadimplência.", icone: "📅" },
          { titulo: "Conciliação bancária", descricao: "Compare lançamentos do sistema com o extrato do banco.", icone: "🏦" },
          { titulo: "DRE automático", descricao: "Demonstrativo de resultados gerado automaticamente.", icone: "📈" },
        ],
      },
      "emissao-fiscal": {
        titulo: "Emissão Fiscal",
        subtitulo: "NFC-e e NF-e integradas e sem complicação",
        descricao: "Emita notas fiscais de consumidor e notas fiscais eletrônicas diretamente pelo sistema, com total conformidade fiscal.",
        icone: "📑",
        recursos: [
          { titulo: "NFC-e automática", descricao: "Nota fiscal de consumidor gerada a cada venda.", icone: "🧾" },
          { titulo: "NF-e completa", descricao: "Emissão de nota fiscal eletrônica para fornecedores e clientes.", icone: "📄" },
          { titulo: "Cancelamento e inutilização", descricao: "Gerencie notas canceladas e inutilizadas sem burocracia.", icone: "❌" },
          { titulo: "Relatório fiscal", descricao: "Consulte todas as notas emitidas com filtros avançados.", icone: "🔍" },
        ],
      },
      "relatorios-gerenciais": {
        titulo: "Relatórios Gerenciais",
        subtitulo: "Dados estratégicos para tomar decisões melhores",
        descricao: "Dashboards e relatórios detalhados com ticket médio, produtos mais vendidos, DRE e muito mais — tudo atualizado em tempo real.",
        icone: "📊",
        recursos: [
          { titulo: "Dashboard em tempo real", descricao: "Indicadores do dia atualizados automaticamente.", icone: "📈" },
          { titulo: "Ticket médio", descricao: "Acompanhe o valor médio das vendas por período.", icone: "🎫" },
          { titulo: "Ranking de produtos", descricao: "Saiba quais itens mais vendem e quais estão encalhados.", icone: "🏆" },
          { titulo: "Relatório por garçom", descricao: "Meça a performance de cada atendente.", icone: "👤" },
        ],
      },
    },

    // ── Parceiros ────────────────────────────────────────────────────────────
    parceiros: {
      seloPagina: "Programa de Parceiros",
      tituloPagina: "Cresça com o Big Chef",
      subtituloPagina: "Seja um parceiro comercial e ganhe comissões recorrentes indicando o sistema de gestão que está revolucionando a gastronomia.",
      seloSobre: "Quem somos",
      tituloSobre: "Conheça a Word System",
      descricaoSobre: "Desenvolvemos soluções completas de gestão para o setor de alimentação fora do lar há mais de uma década.",
      descricaoEmpresa: "Especializada no desenvolvimento de sistemas para bares, restaurantes, lanchonetes e delivery.",
      sede: "Santa Fé — PR, Brasil",
      cnpjLabel: "Empresa registrada e ativa desde 2016",
      atuacao: "Todo o território nacional",
      numeros: [
        { valor: "+10", rotulo: "Anos no mercado", icone: "📅" },
        { valor: "+3.000", rotulo: "Clientes ativos", icone: "👥" },
        { valor: "+15.000", rotulo: "Estabelecimentos gerenciados", icone: "🏪" },
        { valor: "24/7", rotulo: "Suporte disponível", icone: "🎧" },
      ],
      motivosParceiro: [
        "Mercado de food service em constante crescimento",
        "Produto consolidado e atualizado semanalmente",
        "Mais de 3.000 clientes ativos em todo o Brasil",
        "Alta taxa de conversão e retenção de clientes",
        "Suporte completo para fechar negócios",
        "Comissões recorrentes e previsíveis",
      ],
      vantagens: [
        { icone: "💰", titulo: "Comissão Recorrente", descricao: "Receba comissões mensais por cada cliente ativo indicado por você." },
        { icone: "📦", titulo: "Material de Apoio", descricao: "Acesso a materiais de marketing, apresentações e conteúdos exclusivos." },
        { icone: "🎓", titulo: "Treinamento Especializado", descricao: "Capacitação completa sobre o sistema para você vender com confiança." },
        { icone: "🤝", titulo: "Suporte Dedicado", descricao: "Canal direto com nosso time comercial para tirar dúvidas e fechar negócios." },
        { icone: "📈", titulo: "Painel do Parceiro", descricao: "Acompanhe suas indicações, comissões e desempenho em tempo real." },
        { icone: "🚀", titulo: "Sem Investimento Inicial", descricao: "Torne-se parceiro sem nenhum custo. Basta se cadastrar e começar." },
      ],
      comoFunciona: [
        { passo: "1", titulo: "Cadastre-se", descricao: "Preencha o formulário com seus dados e aguarde a aprovação." },
        { passo: "2", titulo: "Receba seu acesso", descricao: "Após aprovado, você terá acesso ao painel e materiais de apoio." },
        { passo: "3", titulo: "Indique clientes", descricao: "Compartilhe seu link exclusivo e apresente o sistema para potenciais clientes." },
        { passo: "4", titulo: "Receba comissões", descricao: "A cada cliente que assinar, você recebe comissão recorrente." },
      ],
      itensLateral: [
        "Comissão **recorrente** mensal",
        "Material de marketing **exclusivo**",
        "Treinamento **completo** sobre o produto",
        "Suporte **dedicado** do time comercial",
        "Painel para acompanhar **indicações e ganhos**",
        "**Sem investimento** inicial",
      ],
      perfisIdeais: ["Consultores de TI", "Contadores", "Vendedores autônomos", "Empresas de tecnologia", "Revendedores de software"],
    },

    // ── Páginas de Segmentos ──────────────────────────────────────────────────
    paginasSegmentos: {
      "restaurantes": {
        titulo: "Sistema para Restaurantes",
        subtitulo: "A solução completa para o seu restaurante",
        descricao: "Do atendimento no salão até a gestão financeira, o Big Chef oferece tudo que seu restaurante precisa para operar com eficiência e crescer.",
        icone: "🍽️",
        beneficios: [
          { titulo: "Gestão de mesas e comandas", descricao: "Organize o salão com mapa visual de mesas e comandas individuais.", icone: "🗺️" },
          { titulo: "PDV rápido", descricao: "Atendimento no caixa em segundos com suporte a código de barras.", icone: "🏪" },
          { titulo: "Delivery integrado", descricao: "Receba pedidos online no seu próprio canal, sem taxas abusivas.", icone: "🛵" },
          { titulo: "Emissão fiscal automática", descricao: "NFC-e e NF-e geradas automaticamente a cada venda.", icone: "📑" },
        ],
      },
      "bares-e-baladas": {
        titulo: "Sistema para Bares e Baladas",
        subtitulo: "Controle total para operações noturnas",
        descricao: "Gerencie comandas, mesas e atendimento em alta velocidade. Ideal para bares, pubs e casas noturnas com grande volume de clientes.",
        icone: "🍺",
        beneficios: [
          { titulo: "Comandas rápidas", descricao: "Abertura e fechamento de comandas em segundos.", icone: "⚡" },
          { titulo: "Controle de estoque", descricao: "Monitore bebidas e insumos em tempo real.", icone: "📦" },
          { titulo: "Divisão de conta", descricao: "Divida por igual ou por consumo — sem confusão.", icone: "➗" },
          { titulo: "App do garçom", descricao: "Pedidos direto do celular para o bar instantaneamente.", icone: "📱" },
        ],
      },
      "cafeterias": {
        titulo: "Sistema para Cafeterias",
        subtitulo: "Agilidade e charme para o seu café",
        descricao: "PDV rápido no balcão, controle de estoque de insumos e relatórios para saber exatamente o que mais vende na sua cafeteria.",
        icone: "☕",
        beneficios: [
          { titulo: "PDV de balcão", descricao: "Atendimento rápido no caixa, perfeito para fluxo contínuo.", icone: "🏪" },
          { titulo: "Programa de fidelidade", descricao: "Fidelize clientes com cartão digital de pontos.", icone: "⭐" },
          { titulo: "Controle de insumos", descricao: "Saiba exatamente quanto gasta em cada receita.", icone: "📊" },
          { titulo: "Relatórios de vendas", descricao: "Identifique seus campeões de venda e otimize o cardápio.", icone: "📈" },
        ],
      },
      "dark-kitchens": {
        titulo: "Sistema para Dark Kitchens",
        subtitulo: "Gestão focada 100% em delivery",
        descricao: "Sem salão, sem complicação. O Big Chef automatiza o recebimento de pedidos, integra com marketplaces e otimiza sua operação de cozinha.",
        icone: "🏭",
        beneficios: [
          { titulo: "Integração com iFood e AiqFome", descricao: "Receba pedidos de todos os canais em um só lugar.", icone: "🔗" },
          { titulo: "Chatbot WhatsApp", descricao: "Pedidos automáticos pelo WhatsApp, 24 horas por dia.", icone: "🤖" },
          { titulo: "Painel de produção", descricao: "Organize pedidos por prioridade na cozinha.", icone: "📋" },
          { titulo: "Relatório de performance", descricao: "Tempo médio de preparo, taxa de cancelamento e mais.", icone: "📊" },
        ],
      },
      "sistema-para-delivery": {
        titulo: "Sistema para Delivery",
        subtitulo: "Seu delivery profissional sem taxas abusivas",
        descricao: "Monte seu próprio canal de delivery com cardápio digital, chatbot no WhatsApp e integração com os principais marketplaces do Brasil.",
        icone: "🛵",
        beneficios: [
          { titulo: "Site próprio de delivery", descricao: "Cardápio online com seu domínio e sua marca.", icone: "🌐" },
          { titulo: "Chatbot para WhatsApp", descricao: "Receba pedidos automáticos pelo WhatsApp.", icone: "💬" },
          { titulo: "Rastreamento de pedido", descricao: "Cliente acompanha o status do pedido em tempo real.", icone: "📍" },
          { titulo: "Gestão de entregadores", descricao: "Controle rotas e atribuições dos motoboys.", icone: "🏍️" },
        ],
      },
    },
  },
};
