// ╔════════════════════════════════════════════════════════════════════════════╗
// ║  MULHERZ — Definição do Flavor                                            ║
// ║                                                                           ║
// ║  Cores, imagens, sombras, configuração e textos do sistema Mulherz.       ║
// ║  TODO: substituir URLs de logo, links, contatos e downloads.              ║
// ╚════════════════════════════════════════════════════════════════════════════╝

import type { Flavor } from "./types";

// ── URLs externas ───────────────────────────────────────────────────────────

const URL_APP_STORE = "https://apps.apple.com/br/app/TODO-mulherz";
const URL_PLAY_STORE = "https://play.google.com/store/apps/details?id=br.com.TODO.mulherz";

export const mulherz: Flavor = {
  id: "mulherz",

  // Paleta rosa/roxo feminina
  cores: {
    primaria: "#E91E8C",
    primariaEscura: "#C01270",
    primariaClara: "#FDE9F5",
    destaque: "#9B59B6",
    escura: "#2D002D",
    clara: "#FFFFFF",
    borda: "#E5E7EB",
    textoSuave: "#4B5563",
    textoDesabilitado: "#9CA3AF",
    secundaria: "#FDE9F5",
  },

  imagens: {
    gifHeroi: "https://via.placeholder.com/800x500?text=Mulherz+Preview",
    preVisualizacaoPainel: "https://via.placeholder.com/1200x700?text=Mulherz+Dashboard",
    simulacaoWhatsapp: "https://via.placeholder.com/400x600?text=Mulherz+WhatsApp",
    depoimento1: "https://via.placeholder.com/60x60?text=aspas",
    aiqfome: "https://aiqfome.com/assets/images/logo.svg",
    ifood: "https://www.ifood.com.br/static/images/logo.svg",
  },

  sombras: {
    cabecalho: "0 4px 30px rgba(0,0,0,0.05)",
    imagemPainel: "0 20px 50px rgba(0,0,0,0.1)",
    ctaPadrao: "0 8px 20px rgba(233,30,140,0.3)",
    ctaHover: "0 8px 25px rgba(233,30,140,0.4)",
    botaoHeroiPrimario: "0 10px 40px rgba(233,30,140,0.4)",
    botaoPreco: "0 10px 30px rgba(233,30,140,0.3)",
    botaoPrecoHover: "0 10px 35px rgba(233,30,140,0.4)",
    cardFuncionalidade: "0 10px 40px rgba(233,30,140,0.08)",
    planoSelecionado: "0 6px 20px rgba(233,30,140,0.3)",
  },

  configuracao: {
    nome: "Mulherz",
    nomePro: "Mulherz Pro",
    slogan: "Sistema para o seu Negócio",
    nomeEmpresa: "TODO — Empresa do Mulherz",
    descricao: "Plataforma de gestão completa desenvolvida para empreendedoras.",
    logo: "https://via.placeholder.com/200x60?text=Mulherz",
    logoColorida: "https://via.placeholder.com/200x60?text=Mulherz",
    diasTeste: 7,

    secoes: ['heroi', 'appGarcom', 'funcionalidades', 'estatisticas', 'suporte', 'contato', 'chamadaFinal'],
    cabecalho: true,
    rodape: true,

    // Visual minimalista e clean para público feminino
    variantesInicio: {
      heroi: 'minimalista',
      appGarcom: 'compacto',
      funcionalidades: 'padrao',
      estatisticas: 'claro',
      suporte: 'padrao',
      contato: 'centralizado',
      chamadaFinal: 'padrao',
    },

    // ── Configuração por plataforma ──────────────────────────────────────────
    plataformas: {
      // ── Windows ──────────────────────────────────────────────────────────
      'windows': {
        nome: 'Mulherz para Windows',
        slogan: 'O sistema ideal para o seu computador',
        descricao: 'Instale o Mulherz no Windows e tenha performance máxima para gerenciar seu negócio.',
        menus: {
          funcionalidades: {
            rotulo: "Funcionalidades",
            prefixoRota: "/funcionalidades",
            itens: [
              { rotulo: "Frente de Caixa (PDV)", slug: "frente-de-caixa-pdv" },
              { rotulo: "Mesas e Comandas", slug: "mesas-e-comandas" },
              { rotulo: "Financeiro", slug: "financeiro" },
              { rotulo: "Emissão Fiscal", slug: "emissao-fiscal" },
              { rotulo: "Relatórios Gerenciais", slug: "relatorios-gerenciais" },
            ],
          },
        },
        textos: {
          heroi: {
            selo: 'Sistema nativo para Windows',
            tituloAntes: 'Gerencie seu negócio no',
            tituloDestaque: 'seu computador',
            subtitulo: 'Instale o Mulherz no Windows e tenha um sistema rápido, estável e completo para o dia a dia do seu negócio.',
            ctaPrimario: 'Começar {trialDays} dias grátis',
            ctaSecundario: 'Ver sistema funcionando',
          },
          funcionalidades: {
            titulo: 'Performance nativa no Windows',
            subtitulo: 'Sistema instalado com velocidade máxima e funcionamento offline.',
            cartoes: [
              { icone: '⚡', titulo: 'Velocidade Nativa', descricao: 'O sistema roda direto no seu computador — sem lentidão de navegador.' },
              { icone: '🏪', titulo: 'PDV Completo', descricao: 'Frente de caixa com leitura de código de barras e balanças.' },
              { icone: '💰', titulo: 'Financeiro', descricao: 'Controle completo de receitas, despesas e fluxo de caixa.' },
              { icone: '📑', titulo: 'Emissão Fiscal', descricao: 'NFC-e e NF-e integradas ao sistema.' },
              { icone: '📊', titulo: 'Relatórios', descricao: 'Dashboards e relatórios atualizados em tempo real.' },
            ],
          },
          chamadaFinal: {
            selo: 'Sem cartão de crédito',
            titulo: 'Pronta para instalar o Mulherz?',
            subtitulo: 'Baixe agora e teste por {trialDays} dias grátis com todos os módulos, sem compromisso.',
            ctaPrimario: 'Começar {trialDays} dias grátis',
            ctaSecundario: 'Ver planos e preços',
          },
          cadastro: {
            seloTeste: 'dias grátis · sem cartão',
            tituloFormulario: 'Crie sua conta no Mulherz Desktop',
            subtituloFormulario: 'Preencha os dados e baixe o sistema para seu computador.',
            campoEstabelecimento: 'Nome do seu negócio',
            placeholderCampoEstabelecimento: 'Ex: Doceria da Maria',
            seloRiscoLateral: 'Sem risco',
            tituloLateral: 'Performance máxima no seu PC!',
            itensLateral: [
              'Sem precisar cadastrar cartão de crédito',
              'Acesso a **todos os módulos** durante o teste',
              'Sistema nativo com **performance máxima**',
              'Funciona **mesmo sem internet**',
              'Cancele quando quiser, sem burocracia',
            ],
            rotuloModulosLateral: 'Módulos inclusos no teste:',
            modulosLateral: ['PDV Rápido', 'Mesas', 'Delivery', 'Comandas', 'NFC-e / NF-e', 'Financeiro', 'App Garçom', 'Relatórios'],
          },
          download: {
            tituloSecao: 'Baixar o Mulherz para Windows',
            prefixoOsDetectado: 'Detectamos que você usa',
            osDesconhecido: 'Escolha sua plataforma abaixo',
            prefixoBotaoDownload: 'Baixar para',
            botaoOutrasPlataformas: 'Baixar para outra plataforma',
            tituloPassos: 'Como começar em 3 passos',
            passos: [
              { titulo: 'Baixe e instale', descricao: 'Clique no botão acima e execute o instalador. Leva menos de 2 minutos.' },
              { titulo: 'Faça login', descricao: 'Entre com seu e-mail e senha. Seus módulos já estão liberados.' },
              { titulo: 'Configure seu negócio', descricao: 'Cadastre produtos, mesas e comece a vender.' },
            ],
            tituloRequisitos: 'Requisitos do sistema',
            rotuloDesktop: 'Computador (PDV / Painel)',
            rotuloMobile: 'Celular (App Atendente)',
          },
          planos: {
            seloHeroi: 'dias grátis, sem cartão de crédito',
            tituloHeroi: 'Mulherz Desktop: o plano perfeito para o seu negócio',
            subtituloHeroi: 'Instale no Windows e teste por {trialDays} dias grátis com todos os módulos. Performance nativa e funcionamento offline para empreendedoras exigentes.',
          },
          paginasFuncionalidades: {
            'frente-de-caixa-pdv': {
              titulo: 'Frente de Caixa (PDV) — Windows',
              subtitulo: 'Atendimento presencial com velocidade nativa',
              descricao: 'O PDV do Mulherz Desktop roda direto no seu computador com suporte a código de barras, balanças e impressoras térmicas. Funciona mesmo sem internet.',
              icone: '🏪',
              recursos: [
                { titulo: 'Leitura de código de barras', descricao: 'Escaneie produtos instantaneamente sem depender de conexão.', icone: '📷' },
                { titulo: 'Integração com balanças', descricao: 'Peso capturado automaticamente direto no sistema local.', icone: '⚖️' },
                { titulo: 'Múltiplas formas de pagamento', descricao: 'Dinheiro, cartão, Pix e vouchers em uma única venda.', icone: '💳' },
                { titulo: 'Modo offline completo', descricao: 'Continue vendendo sem internet — tudo sincroniza depois.', icone: '📶' },
              ],
            },
            'mesas-e-comandas': {
              titulo: 'Mesas e Comandas — Windows',
              subtitulo: 'Organize seu salão com performance nativa',
              descricao: 'Gerencie mesas, comandas individuais e divisão de contas com velocidade máxima. O sistema instalado garante resposta instantânea nos horários de pico.',
              icone: '🧾',
              recursos: [
                { titulo: 'Mapa de mesas visual', descricao: 'Veja o status de cada mesa em tempo real no seu monitor.', icone: '🗺️' },
                { titulo: 'Comandas individuais', descricao: 'Cada cliente com sua comanda, sem confusão.', icone: '📝' },
                { titulo: 'Divisão de conta', descricao: 'Divida por igual ou por consumo individual com agilidade.', icone: '➗' },
                { titulo: 'Transferência de mesa', descricao: 'Mova clientes de mesa sem perder nenhum pedido.', icone: '🔄' },
              ],
            },
            'financeiro': {
              titulo: 'Financeiro — Windows',
              subtitulo: 'Suas finanças seguras no seu computador',
              descricao: 'Controle receitas, despesas, contas a pagar e receber localmente. Dados financeiros protegidos no seu próprio PC com acesso instantâneo.',
              icone: '💰',
              recursos: [
                { titulo: 'Fluxo de caixa local', descricao: 'Entradas e saídas atualizadas em tempo real no seu computador.', icone: '📊' },
                { titulo: 'Contas a pagar e receber', descricao: 'Organize vencimentos e evite surpresas com alertas automáticos.', icone: '📅' },
                { titulo: 'Conciliação bancária', descricao: 'Compare lançamentos do sistema com o extrato do banco.', icone: '🏦' },
                { titulo: 'DRE automático', descricao: 'Demonstrativo de resultados gerado localmente sem latência.', icone: '📈' },
              ],
            },
            'emissao-fiscal': {
              titulo: 'Emissão Fiscal — Windows',
              subtitulo: 'Notas fiscais com velocidade e estabilidade',
              descricao: 'Emita NFC-e e NF-e direto do sistema instalado, com comunicação direta à SEFAZ. Sem depender de navegador ou conexão instável.',
              icone: '📑',
              recursos: [
                { titulo: 'NFC-e automática', descricao: 'Nota emitida instantaneamente a cada venda.', icone: '🧾' },
                { titulo: 'NF-e completa', descricao: 'Nota fiscal eletrônica para fornecedores e clientes.', icone: '📄' },
                { titulo: 'Cancelamento e inutilização', descricao: 'Gerencie notas canceladas e inutilizadas sem burocracia.', icone: '❌' },
                { titulo: 'Relatório fiscal', descricao: 'Consulte todas as notas emitidas com filtros avançados.', icone: '🔍' },
              ],
            },
            'relatorios-gerenciais': {
              titulo: 'Relatórios Gerenciais — Windows',
              subtitulo: 'Decisões estratégicas com dados locais',
              descricao: 'Dashboards e relatórios processados localmente no seu computador. Ticket médio, ranking de produtos e DRE — tudo instantâneo.',
              icone: '📊',
              recursos: [
                { titulo: 'Dashboard em tempo real', descricao: 'Indicadores do dia atualizados sem depender de internet.', icone: '📈' },
                { titulo: 'Ticket médio', descricao: 'Acompanhe o valor médio das vendas por período.', icone: '🎫' },
                { titulo: 'Ranking de produtos', descricao: 'Saiba quais itens mais vendem e otimize seu cardápio.', icone: '🏆' },
                { titulo: 'Relatório por atendente', descricao: 'Meça a performance de cada profissional da sua equipe.', icone: '👤' },
              ],
            },
          },
          paginasSegmentos: {
            'restaurantes': {
              titulo: 'Mulherz Desktop para Restaurantes',
              subtitulo: 'Performance nativa para a operação do seu restaurante',
              descricao: 'Com o Mulherz Desktop instalado no Windows, seu restaurante opera com velocidade máxima. Do salão à gestão financeira, tudo funciona mesmo sem internet.',
              icone: '🍽️',
              beneficios: [
                { titulo: 'Gestão de mesas e comandas', descricao: 'Organize o salão com mapa visual e comandas individuais sem lentidão.', icone: '🗺️' },
                { titulo: 'PDV ultra-rápido', descricao: 'Atendimento no caixa instantâneo com código de barras e balanças.', icone: '🏪' },
                { titulo: 'Funcionamento offline', descricao: 'Continue operando normalmente mesmo sem internet.', icone: '📶' },
                { titulo: 'Emissão fiscal integrada', descricao: 'NFC-e e NF-e emitidas direto do sistema local.', icone: '📑' },
              ],
            },
            'bares-e-baladas': {
              titulo: 'Mulherz Desktop para Bares e Baladas',
              subtitulo: 'Velocidade máxima para operações noturnas',
              descricao: 'Gerencie comandas e mesas em alta velocidade com o Mulherz Desktop. Performance nativa ideal para bares, pubs e casas noturnas.',
              icone: '🍺',
              beneficios: [
                { titulo: 'Comandas instantâneas', descricao: 'Abertura e fechamento de comandas sem travamentos.', icone: '⚡' },
                { titulo: 'Controle de estoque local', descricao: 'Monitore bebidas e insumos direto no seu computador.', icone: '📦' },
                { titulo: 'Divisão de conta ágil', descricao: 'Divida por igual ou por consumo com velocidade nativa.', icone: '➗' },
                { titulo: 'App do garçom integrado', descricao: 'Pedidos do celular direto para o bar instantaneamente.', icone: '📱' },
              ],
            },
            'cafeterias': {
              titulo: 'Mulherz Desktop para Cafeterias',
              subtitulo: 'Agilidade nativa para o seu café',
              descricao: 'PDV rápido no balcão, controle de insumos e relatórios completos — tudo instalado no seu computador com resposta instantânea.',
              icone: '☕',
              beneficios: [
                { titulo: 'PDV de balcão nativo', descricao: 'Atendimento ultra-rápido no caixa sem depender de internet.', icone: '🏪' },
                { titulo: 'Programa de fidelidade', descricao: 'Fidelize clientes com cartão digital de pontos.', icone: '⭐' },
                { titulo: 'Controle de insumos', descricao: 'Saiba exatamente quanto gasta em cada receita.', icone: '📊' },
                { titulo: 'Relatórios locais', descricao: 'Identifique campeões de venda com dados processados na máquina.', icone: '📈' },
              ],
            },
            'dark-kitchens': {
              titulo: 'Mulherz Desktop para Dark Kitchens',
              subtitulo: 'Gestão de delivery com performance nativa',
              descricao: 'Automatize pedidos, integre com marketplaces e organize a cozinha com o Mulherz Desktop. Processamento local garante estabilidade total.',
              icone: '🏭',
              beneficios: [
                { titulo: 'Integração com marketplaces', descricao: 'Receba pedidos de todos os canais direto no seu computador.', icone: '🔗' },
                { titulo: 'Painel de produção local', descricao: 'Organize pedidos por prioridade com velocidade nativa.', icone: '📋' },
                { titulo: 'Operação offline', descricao: 'Continue processando pedidos mesmo sem internet.', icone: '📶' },
                { titulo: 'Relatório de performance', descricao: 'Tempo de preparo, cancelamentos e métricas — processados localmente.', icone: '📊' },
              ],
            },
            'sistema-para-delivery': {
              titulo: 'Mulherz Desktop para Delivery',
              subtitulo: 'Delivery profissional com estabilidade nativa',
              descricao: 'Monte seu canal de delivery com cardápio digital e chatbot no WhatsApp. O Mulherz Desktop processa tudo localmente com máxima estabilidade.',
              icone: '🛵',
              beneficios: [
                { titulo: 'Site próprio de delivery', descricao: 'Cardápio online com sua marca e seu domínio.', icone: '🌐' },
                { titulo: 'Chatbot para WhatsApp', descricao: 'Pedidos automáticos pelo WhatsApp integrados ao sistema local.', icone: '💬' },
                { titulo: 'Rastreamento de pedido', descricao: 'Status em tempo real para suas clientes.', icone: '📍' },
                { titulo: 'Gestão de entregadores', descricao: 'Controle rotas e atribuições direto do computador.', icone: '🏍️' },
              ],
            },
          },
          parceiros: {
            seloPagina: 'Programa de Parceiras',
            tituloPagina: 'Cresça com o Mulherz Desktop',
            subtituloPagina: 'Seja uma parceira comercial e ganhe comissões recorrentes indicando o sistema desktop com performance nativa feito para empreendedoras.',
            seloSobre: 'Quem somos',
            tituloSobre: 'Conheça a Word System',
            descricaoSobre: 'Desenvolvemos soluções de gestão com performance nativa para empreendedoras do setor de alimentação.',
            descricaoEmpresa: 'Especializada no desenvolvimento de sistemas instalados localmente para bares, restaurantes, cafeterias e delivery.',
            sede: 'Maringá — PR, Brasil',
            cnpjLabel: 'Empresa registrada e ativa desde 2016',
            atuacao: 'Todo o território nacional',
            numeros: [
              { valor: '+10', rotulo: 'Anos no mercado', icone: '📅' },
              { valor: '+3.000', rotulo: 'Clientes ativas', icone: '👥' },
              { valor: '+15.000', rotulo: 'Estabelecimentos gerenciados', icone: '🏪' },
              { valor: '24/7', rotulo: 'Suporte disponível', icone: '🎧' },
            ],
            motivosParceiro: [
              'Sistema desktop com performance nativa — diferencial competitivo',
              'Funciona offline, ideal para regiões com internet instável',
              'Mais de 3.000 clientes ativas em todo o Brasil',
              'Alta taxa de conversão e retenção',
              'Suporte completo com instalação remota inclusa',
              'Comissões recorrentes e previsíveis',
            ],
            vantagens: [
              { icone: '💰', titulo: 'Comissão Recorrente', descricao: 'Receba comissões mensais por cada cliente ativa indicada por você.' },
              { icone: '📦', titulo: 'Material de Apoio', descricao: 'Materiais de marketing e apresentações prontas sobre o sistema desktop.' },
              { icone: '🎓', titulo: 'Treinamento Especializado', descricao: 'Capacitação completa sobre o sistema instalado para vender com confiança.' },
              { icone: '🤝', titulo: 'Suporte Dedicado', descricao: 'Canal direto com nosso time comercial para fechar negócios.' },
              { icone: '📈', titulo: 'Painel da Parceira', descricao: 'Acompanhe indicações, comissões e desempenho em tempo real.' },
              { icone: '🚀', titulo: 'Sem Investimento Inicial', descricao: 'Torne-se parceira sem nenhum custo. Cadastre-se e comece.' },
            ],
            comoFunciona: [
              { passo: '1', titulo: 'Cadastre-se', descricao: 'Preencha o formulário com seus dados e aguarde a aprovação.' },
              { passo: '2', titulo: 'Receba seu acesso', descricao: 'Após aprovada, você terá acesso ao painel e materiais de apoio.' },
              { passo: '3', titulo: 'Indique clientes', descricao: 'Compartilhe seu link exclusivo e apresente o Mulherz Desktop.' },
              { passo: '4', titulo: 'Receba comissões', descricao: 'A cada cliente que assinar, você recebe comissão recorrente.' },
            ],
            itensLateral: [
              'Comissão **recorrente** mensal',
              'Material de marketing **exclusivo**',
              'Treinamento **completo** sobre o produto desktop',
              'Suporte **dedicado** do time comercial',
              'Painel para acompanhar **indicações e ganhos**',
              '**Sem investimento** inicial',
            ],
            perfisIdeais: ['Consultoras de TI', 'Contadoras', 'Vendedoras autônomas', 'Empresas de tecnologia', 'Revendedoras de software'],
          },
        },
      },

      // ── Mac ──────────────────────────────────────────────────────────────
      'mac': {
        nome: 'Mulherz para Mac',
        slogan: 'O sistema ideal para quem usa Apple',
        descricao: 'O Mulherz funciona perfeitamente no macOS. Gerencie seu negócio com estilo e eficiência.',
        textos: {
          heroi: {
            selo: 'Compatível com macOS',
            tituloAntes: 'Gerencie seu negócio no',
            tituloDestaque: 'seu Mac',
            subtitulo: 'O Mulherz é totalmente compatível com macOS. Acesse pelo navegador e tenha a mesma experiência completa do sistema.',
            ctaPrimario: 'Começar {trialDays} dias grátis',
            ctaSecundario: 'Conhecer o sistema',
          },
          chamadaFinal: {
            selo: 'Sem cartão de crédito',
            titulo: 'Pronta para usar o Mulherz no Mac?',
            subtitulo: 'Teste por {trialDays} dias grátis com todos os módulos, sem compromisso.',
            ctaPrimario: 'Começar {trialDays} dias grátis',
            ctaSecundario: 'Ver planos e preços',
          },
          planos: {
            seloHeroi: 'dias grátis, sem cartão de crédito',
            tituloHeroi: 'Mulherz para Mac: gerencie direto do seu Apple',
            subtituloHeroi: 'Acesse pelo navegador no macOS e teste por {trialDays} dias grátis. Todos os módulos liberados, sem instalação.',
          },
          paginasFuncionalidades: {
            'frente-de-caixa-pdv': {
              titulo: 'Frente de Caixa (PDV) — macOS',
              subtitulo: 'Atendimento rápido direto do seu Mac',
              descricao: 'Acesse o PDV do Mulherz pelo navegador no macOS. Leitura de código de barras, múltiplos pagamentos e interface otimizada para o ecossistema Apple.',
              icone: '🏪',
              recursos: [
                { titulo: 'Acesso via navegador', descricao: 'Abra no Safari ou Chrome e comece a vender imediatamente.', icone: '🌐' },
                { titulo: 'Leitura de código de barras', descricao: 'Escaneie produtos com leitores compatíveis com macOS.', icone: '📷' },
                { titulo: 'Múltiplas formas de pagamento', descricao: 'Dinheiro, cartão, Pix e vouchers em uma única venda.', icone: '💳' },
                { titulo: 'Interface responsiva', descricao: 'Design adaptado para telas Retina e trackpad.', icone: '🖥️' },
              ],
            },
            'mesas-e-comandas': {
              titulo: 'Mesas e Comandas — macOS',
              subtitulo: 'Organize seu salão pelo Mac',
              descricao: 'Gerencie mesas e comandas pelo navegador no macOS. Mapa visual do salão e divisão de contas com a elegância do ecossistema Apple.',
              icone: '🧾',
              recursos: [
                { titulo: 'Mapa de mesas visual', descricao: 'Veja o status de cada mesa em tempo real no seu Mac.', icone: '🗺️' },
                { titulo: 'Comandas individuais', descricao: 'Cada cliente com sua comanda, sem confusão.', icone: '📝' },
                { titulo: 'Divisão de conta', descricao: 'Divida por igual ou por consumo individual.', icone: '➗' },
                { titulo: 'Transferência de mesa', descricao: 'Mova clientes sem perder pedidos registrados.', icone: '🔄' },
              ],
            },
            'chatbot-para-delivery': {
              titulo: 'Chatbot para Delivery — macOS',
              subtitulo: 'Delivery automatizado no seu Mac',
              descricao: 'Configure e gerencie seu delivery pelo navegador no macOS. Chatbot inteligente para WhatsApp e cardápio digital com a praticidade Apple.',
              icone: '🛵',
              recursos: [
                { titulo: 'Cardápio digital', descricao: 'Seu cardápio online sempre atualizado, gerenciado pelo Mac.', icone: '📱' },
                { titulo: 'Chatbot WhatsApp', descricao: 'Atendimento automático 24h configurado pelo navegador.', icone: '🤖' },
                { titulo: 'Acompanhamento de pedido', descricao: 'Status em tempo real para suas clientes.', icone: '📍' },
                { titulo: 'Integração com marketplaces', descricao: 'iFood e outros integrados ao sistema.', icone: '🔗' },
              ],
            },
            'financeiro': {
              titulo: 'Financeiro — macOS',
              subtitulo: 'Finanças sob controle no seu Mac',
              descricao: 'Controle receitas, despesas e fluxo de caixa pelo navegador no macOS. Interface limpa e organizada para empreendedoras que usam Apple.',
              icone: '💰',
              recursos: [
                { titulo: 'Fluxo de caixa', descricao: 'Entradas e saídas atualizadas em tempo real.', icone: '📊' },
                { titulo: 'Contas a pagar e receber', descricao: 'Organize vencimentos e cobranças pelo Mac.', icone: '📅' },
                { titulo: 'Conciliação bancária', descricao: 'Compare lançamentos com o extrato do banco.', icone: '🏦' },
                { titulo: 'DRE automático', descricao: 'Resultados gerados automaticamente no navegador.', icone: '📈' },
              ],
            },
            'emissao-fiscal': {
              titulo: 'Emissão Fiscal — macOS',
              subtitulo: 'Notas fiscais direto do Mac',
              descricao: 'Emita NFC-e e NF-e pelo navegador no macOS. Conformidade fiscal sem complicação, com a praticidade do ecossistema Apple.',
              icone: '📑',
              recursos: [
                { titulo: 'NFC-e automática', descricao: 'Nota de consumidor gerada a cada venda.', icone: '🧾' },
                { titulo: 'NF-e completa', descricao: 'Nota eletrônica para fornecedores e clientes.', icone: '📄' },
                { titulo: 'Cancelamento e inutilização', descricao: 'Gerencie notas canceladas facilmente.', icone: '❌' },
                { titulo: 'Relatório fiscal', descricao: 'Consulte notas emitidas com filtros avançados.', icone: '🔍' },
              ],
            },
            'relatorios-gerenciais': {
              titulo: 'Relatórios Gerenciais — macOS',
              subtitulo: 'Dados estratégicos no seu Mac',
              descricao: 'Dashboards e relatórios acessíveis pelo navegador no macOS. Ticket médio, ranking de produtos e indicadores em tempo real.',
              icone: '📊',
              recursos: [
                { titulo: 'Dashboard em tempo real', descricao: 'Indicadores atualizados automaticamente no navegador.', icone: '📈' },
                { titulo: 'Ticket médio', descricao: 'Valor médio das vendas por período.', icone: '🎫' },
                { titulo: 'Ranking de produtos', descricao: 'Seus campeões de venda em destaque.', icone: '🏆' },
                { titulo: 'Relatório por atendente', descricao: 'Performance individual da equipe.', icone: '👤' },
              ],
            },
          },
          paginasSegmentos: {
            'restaurantes': {
              titulo: 'Mulherz para Restaurantes — macOS',
              subtitulo: 'Gestão completa do restaurante no seu Mac',
              descricao: 'Acesse o Mulherz pelo navegador no macOS e gerencie salão, delivery e financeiro do seu restaurante com a elegância Apple.',
              icone: '🍽️',
              beneficios: [
                { titulo: 'Gestão de mesas e comandas', descricao: 'Mapa visual e comandas individuais acessíveis pelo Mac.', icone: '🗺️' },
                { titulo: 'PDV pelo navegador', descricao: 'Atendimento no caixa direto do Safari ou Chrome.', icone: '🏪' },
                { titulo: 'Delivery integrado', descricao: 'Canal próprio sem taxas abusivas.', icone: '🛵' },
                { titulo: 'Emissão fiscal', descricao: 'NFC-e e NF-e emitidas pelo navegador.', icone: '📑' },
              ],
            },
            'bares-e-baladas': {
              titulo: 'Mulherz para Bares e Baladas — macOS',
              subtitulo: 'Agilidade no atendimento pelo Mac',
              descricao: 'Comandas rápidas e controle de estoque acessíveis pelo navegador no macOS. Ideal para bares e casas noturnas.',
              icone: '🍺',
              beneficios: [
                { titulo: 'Comandas rápidas', descricao: 'Abertura e fechamento instantâneos pelo navegador.', icone: '⚡' },
                { titulo: 'Controle de estoque', descricao: 'Monitore bebidas em tempo real.', icone: '📦' },
                { titulo: 'Divisão de conta', descricao: 'Divida por igual ou por consumo.', icone: '➗' },
                { titulo: 'App do garçom', descricao: 'Pedidos sincronizados com o sistema no Mac.', icone: '📱' },
              ],
            },
            'cafeterias': {
              titulo: 'Mulherz para Cafeterias — macOS',
              subtitulo: 'Praticidade Apple para o seu café',
              descricao: 'PDV rápido, controle de insumos e relatórios acessíveis pelo navegador no macOS.',
              icone: '☕',
              beneficios: [
                { titulo: 'PDV de balcão', descricao: 'Atendimento rápido e eficiente pelo navegador.', icone: '🏪' },
                { titulo: 'Programa de fidelidade', descricao: 'Cartão digital de pontos para suas clientes.', icone: '⭐' },
                { titulo: 'Controle de insumos', descricao: 'Saiba o custo de cada receita.', icone: '📊' },
                { titulo: 'Relatórios de vendas', descricao: 'Identifique seus campeões de venda.', icone: '📈' },
              ],
            },
            'dark-kitchens': {
              titulo: 'Mulherz para Dark Kitchens — macOS',
              subtitulo: 'Delivery gerenciado pelo Mac',
              descricao: 'Automatize pedidos e integre com marketplaces direto do navegador no macOS. Gestão de cozinha com praticidade Apple.',
              icone: '🏭',
              beneficios: [
                { titulo: 'Integração com marketplaces', descricao: 'Pedidos centralizados de todos os canais.', icone: '🔗' },
                { titulo: 'Chatbot WhatsApp', descricao: 'Pedidos automáticos 24h.', icone: '🤖' },
                { titulo: 'Painel de produção', descricao: 'Organize pedidos por prioridade.', icone: '📋' },
                { titulo: 'Relatório de performance', descricao: 'Tempo de preparo e métricas.', icone: '📊' },
              ],
            },
            'sistema-para-delivery': {
              titulo: 'Mulherz para Delivery — macOS',
              subtitulo: 'Delivery profissional gerenciado pelo Mac',
              descricao: 'Cardápio digital, chatbot e marketplaces gerenciados pelo navegador no macOS. Delivery com a sua marca e a praticidade Apple.',
              icone: '🛵',
              beneficios: [
                { titulo: 'Site próprio de delivery', descricao: 'Cardápio online com sua marca.', icone: '🌐' },
                { titulo: 'Chatbot para WhatsApp', descricao: 'Pedidos automáticos pelo WhatsApp.', icone: '💬' },
                { titulo: 'Rastreamento de pedido', descricao: 'Status em tempo real.', icone: '📍' },
                { titulo: 'Gestão de entregadores', descricao: 'Controle rotas e atribuições.', icone: '🏍️' },
              ],
            },
          },
          parceiros: {
            seloPagina: 'Programa de Parceiras',
            tituloPagina: 'Cresça com o Mulherz no Mac',
            subtituloPagina: 'Seja uma parceira comercial e indique o Mulherz para empreendedoras que usam macOS. Comissões recorrentes garantidas.',
            seloSobre: 'Quem somos',
            tituloSobre: 'Conheça a Word System',
            descricaoSobre: 'Desenvolvemos soluções de gestão acessíveis pelo navegador, compatíveis com macOS e o ecossistema Apple.',
            descricaoEmpresa: 'Especializada no desenvolvimento de sistemas para bares, restaurantes, cafeterias e delivery.',
            sede: 'Maringá — PR, Brasil',
            cnpjLabel: 'Empresa registrada e ativa desde 2016',
            atuacao: 'Todo o território nacional',
            numeros: [
              { valor: '+10', rotulo: 'Anos no mercado', icone: '📅' },
              { valor: '+3.000', rotulo: 'Clientes ativas', icone: '👥' },
              { valor: '+15.000', rotulo: 'Estabelecimentos gerenciados', icone: '🏪' },
              { valor: '24/7', rotulo: 'Suporte disponível', icone: '🎧' },
            ],
            motivosParceiro: [
              'Sistema compatível com macOS sem instalação',
              'Produto feito para empreendedoras do setor de alimentação',
              'Mais de 3.000 clientes ativas em todo o Brasil',
              'Alta taxa de conversão e retenção',
              'Suporte completo para fechar negócios',
              'Comissões recorrentes e previsíveis',
            ],
            vantagens: [
              { icone: '💰', titulo: 'Comissão Recorrente', descricao: 'Receba comissões mensais por cada cliente ativa indicada.' },
              { icone: '📦', titulo: 'Material de Apoio', descricao: 'Materiais de marketing e apresentações exclusivas.' },
              { icone: '🎓', titulo: 'Treinamento Especializado', descricao: 'Capacitação completa para vender com confiança.' },
              { icone: '🤝', titulo: 'Suporte Dedicado', descricao: 'Canal direto com nosso time comercial.' },
              { icone: '📈', titulo: 'Painel da Parceira', descricao: 'Acompanhe indicações, comissões e desempenho.' },
              { icone: '🚀', titulo: 'Sem Investimento Inicial', descricao: 'Torne-se parceira sem nenhum custo.' },
            ],
            comoFunciona: [
              { passo: '1', titulo: 'Cadastre-se', descricao: 'Preencha o formulário e aguarde a aprovação.' },
              { passo: '2', titulo: 'Receba seu acesso', descricao: 'Após aprovada, acesse o painel e materiais de apoio.' },
              { passo: '3', titulo: 'Indique clientes', descricao: 'Compartilhe seu link e apresente o Mulherz para Mac.' },
              { passo: '4', titulo: 'Receba comissões', descricao: 'A cada cliente que assinar, você recebe comissão recorrente.' },
            ],
            itensLateral: [
              'Comissão **recorrente** mensal',
              'Material de marketing **exclusivo**',
              'Treinamento **completo** sobre o produto',
              'Suporte **dedicado** do time comercial',
              'Painel para acompanhar **indicações e ganhos**',
              '**Sem investimento** inicial',
            ],
            perfisIdeais: ['Consultoras de TI', 'Contadoras', 'Vendedoras autônomas', 'Empresas de tecnologia', 'Revendedoras de software'],
          },
        },
      },

      // ── Linux ────────────────────────────────────────────────────────────
      'linux': {
        nome: 'Mulherz para Linux',
        slogan: 'Compatível com as principais distribuições',
        descricao: 'O Mulherz funciona no Linux via navegador. Gerencie seu negócio sem depender de Windows.',
        textos: {
          heroi: {
            selo: 'Funciona no Linux',
            tituloAntes: 'Gerencie seu negócio no',
            tituloDestaque: 'Linux',
            subtitulo: 'Acesse o Mulherz pelo navegador em Ubuntu, Fedora ou qualquer distribuição Linux. Sem dependência de Windows.',
            ctaPrimario: 'Começar {trialDays} dias grátis',
            ctaSecundario: 'Conhecer o sistema',
          },
          chamadaFinal: {
            selo: 'Sem cartão de crédito',
            titulo: 'Pronta para usar o Mulherz no Linux?',
            subtitulo: 'Teste por {trialDays} dias grátis, sem compromisso.',
            ctaPrimario: 'Começar {trialDays} dias grátis',
            ctaSecundario: 'Ver planos e preços',
          },
          planos: {
            seloHeroi: 'dias grátis, sem cartão de crédito',
            tituloHeroi: 'Mulherz para Linux: liberdade para empreender',
            subtituloHeroi: 'Acesse pelo navegador em qualquer distribuição Linux e teste por {trialDays} dias grátis. Todos os módulos liberados.',
          },
          paginasFuncionalidades: {
            'frente-de-caixa-pdv': {
              titulo: 'Frente de Caixa (PDV) — Linux',
              subtitulo: 'Atendimento rápido em qualquer distribuição',
              descricao: 'Acesse o PDV do Mulherz pelo navegador no Linux. Compatível com Ubuntu, Fedora e outras distros. Sem depender de Windows.',
              icone: '🏪',
              recursos: [
                { titulo: 'Acesso via navegador', descricao: 'Abra no Firefox ou Chrome e comece a vender.', icone: '🌐' },
                { titulo: 'Leitura de código de barras', descricao: 'Escaneie produtos com leitores compatíveis.', icone: '📷' },
                { titulo: 'Múltiplas formas de pagamento', descricao: 'Dinheiro, cartão, Pix e vouchers.', icone: '💳' },
                { titulo: 'Compatibilidade total', descricao: 'Funciona em Ubuntu, Fedora, Mint e mais.', icone: '🐧' },
              ],
            },
            'mesas-e-comandas': {
              titulo: 'Mesas e Comandas — Linux',
              subtitulo: 'Organize seu salão sem depender de Windows',
              descricao: 'Gerencie mesas e comandas pelo navegador no Linux. Mapa visual do salão e divisão de contas com liberdade de escolha.',
              icone: '🧾',
              recursos: [
                { titulo: 'Mapa de mesas visual', descricao: 'Status de cada mesa em tempo real no navegador.', icone: '🗺️' },
                { titulo: 'Comandas individuais', descricao: 'Cada cliente com sua comanda.', icone: '📝' },
                { titulo: 'Divisão de conta', descricao: 'Divida por igual ou por consumo individual.', icone: '➗' },
                { titulo: 'Transferência de mesa', descricao: 'Mova clientes sem perder pedidos.', icone: '🔄' },
              ],
            },
            'chatbot-para-delivery': {
              titulo: 'Chatbot para Delivery — Linux',
              subtitulo: 'Delivery automatizado no Linux',
              descricao: 'Configure e gerencie seu delivery pelo navegador no Linux. Chatbot inteligente para WhatsApp e cardápio digital sem limitações.',
              icone: '🛵',
              recursos: [
                { titulo: 'Cardápio digital', descricao: 'Cardápio online sempre atualizado.', icone: '📱' },
                { titulo: 'Chatbot WhatsApp', descricao: 'Atendimento automático 24h.', icone: '🤖' },
                { titulo: 'Acompanhamento de pedido', descricao: 'Status em tempo real para suas clientes.', icone: '📍' },
                { titulo: 'Integração com marketplaces', descricao: 'iFood e outros integrados.', icone: '🔗' },
              ],
            },
            'financeiro': {
              titulo: 'Financeiro — Linux',
              subtitulo: 'Finanças sob controle em qualquer distro',
              descricao: 'Controle receitas, despesas e fluxo de caixa pelo navegador no Linux. Liberdade e praticidade para empreendedoras.',
              icone: '💰',
              recursos: [
                { titulo: 'Fluxo de caixa', descricao: 'Entradas e saídas em tempo real.', icone: '📊' },
                { titulo: 'Contas a pagar e receber', descricao: 'Organize vencimentos e cobranças.', icone: '📅' },
                { titulo: 'Conciliação bancária', descricao: 'Compare com o extrato do banco.', icone: '🏦' },
                { titulo: 'DRE automático', descricao: 'Resultados gerados automaticamente.', icone: '📈' },
              ],
            },
            'emissao-fiscal': {
              titulo: 'Emissão Fiscal — Linux',
              subtitulo: 'Notas fiscais sem depender de Windows',
              descricao: 'Emita NFC-e e NF-e pelo navegador no Linux. Conformidade fiscal completa com a liberdade do software livre.',
              icone: '📑',
              recursos: [
                { titulo: 'NFC-e automática', descricao: 'Nota de consumidor gerada a cada venda.', icone: '🧾' },
                { titulo: 'NF-e completa', descricao: 'Nota eletrônica para fornecedores e clientes.', icone: '📄' },
                { titulo: 'Cancelamento e inutilização', descricao: 'Gerencie notas facilmente.', icone: '❌' },
                { titulo: 'Relatório fiscal', descricao: 'Consulte notas com filtros avançados.', icone: '🔍' },
              ],
            },
            'relatorios-gerenciais': {
              titulo: 'Relatórios Gerenciais — Linux',
              subtitulo: 'Dados estratégicos no navegador',
              descricao: 'Dashboards e relatórios acessíveis pelo navegador no Linux. Ticket médio, ranking de produtos e indicadores em tempo real.',
              icone: '📊',
              recursos: [
                { titulo: 'Dashboard em tempo real', descricao: 'Indicadores atualizados automaticamente.', icone: '📈' },
                { titulo: 'Ticket médio', descricao: 'Valor médio das vendas por período.', icone: '🎫' },
                { titulo: 'Ranking de produtos', descricao: 'Seus campeões de venda em destaque.', icone: '🏆' },
                { titulo: 'Relatório por atendente', descricao: 'Performance individual da equipe.', icone: '👤' },
              ],
            },
          },
          paginasSegmentos: {
            'restaurantes': {
              titulo: 'Mulherz para Restaurantes — Linux',
              subtitulo: 'Gestão completa sem depender de Windows',
              descricao: 'Acesse o Mulherz pelo navegador no Linux e gerencie salão, delivery e financeiro do seu restaurante com total liberdade.',
              icone: '🍽️',
              beneficios: [
                { titulo: 'Gestão de mesas e comandas', descricao: 'Mapa visual e comandas pelo navegador.', icone: '🗺️' },
                { titulo: 'PDV pelo navegador', descricao: 'Atendimento no caixa via Firefox ou Chrome.', icone: '🏪' },
                { titulo: 'Delivery integrado', descricao: 'Canal próprio sem taxas abusivas.', icone: '🛵' },
                { titulo: 'Emissão fiscal', descricao: 'NFC-e e NF-e pelo navegador.', icone: '📑' },
              ],
            },
            'bares-e-baladas': {
              titulo: 'Mulherz para Bares e Baladas — Linux',
              subtitulo: 'Atendimento ágil no Linux',
              descricao: 'Comandas e controle de estoque acessíveis pelo navegador no Linux. Ideal para bares e casas noturnas.',
              icone: '🍺',
              beneficios: [
                { titulo: 'Comandas rápidas', descricao: 'Abertura e fechamento pelo navegador.', icone: '⚡' },
                { titulo: 'Controle de estoque', descricao: 'Monitore bebidas em tempo real.', icone: '📦' },
                { titulo: 'Divisão de conta', descricao: 'Divida por igual ou por consumo.', icone: '➗' },
                { titulo: 'App do garçom', descricao: 'Pedidos sincronizados com o sistema.', icone: '📱' },
              ],
            },
            'cafeterias': {
              titulo: 'Mulherz para Cafeterias — Linux',
              subtitulo: 'Liberdade e praticidade para o seu café',
              descricao: 'PDV rápido, controle de insumos e relatórios acessíveis pelo navegador em qualquer distribuição Linux.',
              icone: '☕',
              beneficios: [
                { titulo: 'PDV de balcão', descricao: 'Atendimento rápido pelo navegador.', icone: '🏪' },
                { titulo: 'Programa de fidelidade', descricao: 'Cartão digital de pontos.', icone: '⭐' },
                { titulo: 'Controle de insumos', descricao: 'Saiba o custo de cada receita.', icone: '📊' },
                { titulo: 'Relatórios de vendas', descricao: 'Campeões de venda em destaque.', icone: '📈' },
              ],
            },
            'dark-kitchens': {
              titulo: 'Mulherz para Dark Kitchens — Linux',
              subtitulo: 'Delivery gerenciado pelo Linux',
              descricao: 'Automatize pedidos e integre com marketplaces pelo navegador no Linux. Gestão de cozinha com liberdade total.',
              icone: '🏭',
              beneficios: [
                { titulo: 'Integração com marketplaces', descricao: 'Pedidos centralizados de todos os canais.', icone: '🔗' },
                { titulo: 'Chatbot WhatsApp', descricao: 'Pedidos automáticos 24h.', icone: '🤖' },
                { titulo: 'Painel de produção', descricao: 'Organize pedidos por prioridade.', icone: '📋' },
                { titulo: 'Relatório de performance', descricao: 'Métricas e tempo de preparo.', icone: '📊' },
              ],
            },
            'sistema-para-delivery': {
              titulo: 'Mulherz para Delivery — Linux',
              subtitulo: 'Delivery profissional no Linux',
              descricao: 'Cardápio digital, chatbot e marketplaces gerenciados pelo navegador no Linux. Delivery com a sua marca.',
              icone: '🛵',
              beneficios: [
                { titulo: 'Site próprio de delivery', descricao: 'Cardápio online com sua marca.', icone: '🌐' },
                { titulo: 'Chatbot para WhatsApp', descricao: 'Pedidos automáticos pelo WhatsApp.', icone: '💬' },
                { titulo: 'Rastreamento de pedido', descricao: 'Status em tempo real.', icone: '📍' },
                { titulo: 'Gestão de entregadores', descricao: 'Controle rotas e atribuições.', icone: '🏍️' },
              ],
            },
          },
          parceiros: {
            seloPagina: 'Programa de Parceiras',
            tituloPagina: 'Cresça com o Mulherz no Linux',
            subtituloPagina: 'Seja uma parceira comercial e indique o Mulherz para empreendedoras que usam Linux. Comissões recorrentes garantidas.',
            seloSobre: 'Quem somos',
            tituloSobre: 'Conheça a Word System',
            descricaoSobre: 'Desenvolvemos soluções de gestão acessíveis pelo navegador, compatíveis com todas as distribuições Linux.',
            descricaoEmpresa: 'Especializada no desenvolvimento de sistemas para bares, restaurantes, cafeterias e delivery.',
            sede: 'Maringá — PR, Brasil',
            cnpjLabel: 'Empresa registrada e ativa desde 2016',
            atuacao: 'Todo o território nacional',
            numeros: [
              { valor: '+10', rotulo: 'Anos no mercado', icone: '📅' },
              { valor: '+3.000', rotulo: 'Clientes ativas', icone: '👥' },
              { valor: '+15.000', rotulo: 'Estabelecimentos gerenciados', icone: '🏪' },
              { valor: '24/7', rotulo: 'Suporte disponível', icone: '🎧' },
            ],
            motivosParceiro: [
              'Sistema acessível pelo navegador em qualquer distro Linux',
              'Produto feito para empreendedoras do setor de alimentação',
              'Mais de 3.000 clientes ativas em todo o Brasil',
              'Alta taxa de conversão e retenção',
              'Suporte completo para fechar negócios',
              'Comissões recorrentes e previsíveis',
            ],
            vantagens: [
              { icone: '💰', titulo: 'Comissão Recorrente', descricao: 'Receba comissões mensais por cada cliente ativa indicada.' },
              { icone: '📦', titulo: 'Material de Apoio', descricao: 'Materiais de marketing e apresentações exclusivas.' },
              { icone: '🎓', titulo: 'Treinamento Especializado', descricao: 'Capacitação completa para vender com confiança.' },
              { icone: '🤝', titulo: 'Suporte Dedicado', descricao: 'Canal direto com nosso time comercial.' },
              { icone: '📈', titulo: 'Painel da Parceira', descricao: 'Acompanhe indicações, comissões e desempenho.' },
              { icone: '🚀', titulo: 'Sem Investimento Inicial', descricao: 'Torne-se parceira sem nenhum custo.' },
            ],
            comoFunciona: [
              { passo: '1', titulo: 'Cadastre-se', descricao: 'Preencha o formulário e aguarde a aprovação.' },
              { passo: '2', titulo: 'Receba seu acesso', descricao: 'Após aprovada, acesse o painel e materiais de apoio.' },
              { passo: '3', titulo: 'Indique clientes', descricao: 'Compartilhe seu link e apresente o Mulherz para Linux.' },
              { passo: '4', titulo: 'Receba comissões', descricao: 'A cada cliente que assinar, você recebe comissão recorrente.' },
            ],
            itensLateral: [
              'Comissão **recorrente** mensal',
              'Material de marketing **exclusivo**',
              'Treinamento **completo** sobre o produto',
              'Suporte **dedicado** do time comercial',
              'Painel para acompanhar **indicações e ganhos**',
              '**Sem investimento** inicial',
            ],
            perfisIdeais: ['Consultoras de TI', 'Contadoras', 'Vendedoras autônomas', 'Empresas de tecnologia', 'Revendedoras de software'],
          },
        },
      },

      // ── Android ──────────────────────────────────────────────────────────
      'android': {
        nome: 'Mulherz para Android',
        slogan: 'Seu negócio no celular',
        descricao: 'Baixe o app do Mulherz no Android e gerencie pedidos, mesas e muito mais direto do celular.',
        menus: {
          funcionalidades: {
            rotulo: "Funcionalidades",
            prefixoRota: "/funcionalidades",
            itens: [
              { rotulo: "Mesas e Comandas", slug: "mesas-e-comandas" },
              { rotulo: "Chatbot para Delivery", slug: "chatbot-para-delivery" },
            ],
          },
        },
        textos: {
          heroi: {
            selo: 'App nativo para Android',
            tituloAntes: 'Seu negócio na',
            tituloDestaque: 'palma da mão',
            subtitulo: 'Com o app Mulherz para Android, garçons anotam pedidos, a cozinha recebe na hora e você acompanha tudo pelo celular.',
            ctaPrimario: 'Baixar na Play Store',
            ctaSecundario: 'Conhecer o sistema',
          },
          funcionalidades: {
            titulo: 'Tudo no seu celular Android',
            subtitulo: 'App nativo leve e rápido para o dia a dia do seu negócio.',
            cartoes: [
              { icone: '📱', titulo: 'App do Garçom', descricao: 'Anote pedidos direto no celular e envie para a cozinha instantaneamente.' },
              { icone: '🛵', titulo: 'Delivery no Celular', descricao: 'Acompanhe pedidos de delivery em tempo real.' },
              { icone: '📊', titulo: 'Dashboards Mobile', descricao: 'Veja os indicadores do seu negócio de qualquer lugar.' },
            ],
          },
          chamadaFinal: {
            selo: 'Grátis na Play Store',
            titulo: 'Baixe agora no seu Android',
            subtitulo: 'App gratuito com teste de {trialDays} dias de todos os módulos.',
            ctaPrimario: 'Baixar na Play Store',
            ctaSecundario: 'Ver planos e preços',
          },
          planos: {
            seloHeroi: 'dias grátis, sem cartão de crédito',
            tituloHeroi: 'Mulherz para Android: seu negócio no celular',
            subtituloHeroi: 'Baixe o app na Play Store e teste por {trialDays} dias grátis. Gerencie mesas, pedidos e delivery direto do seu Android.',
          },
          paginasFuncionalidades: {
            'mesas-e-comandas': {
              titulo: 'Mesas e Comandas — Android',
              subtitulo: 'Atendimento ágil direto do celular',
              descricao: 'Gerencie mesas e comandas pelo app do Mulherz no Android. Garçons anotam pedidos e enviam para a cozinha instantaneamente.',
              icone: '🧾',
              recursos: [
                { titulo: 'App do garçom', descricao: 'Anote pedidos direto no celular Android.', icone: '📱' },
                { titulo: 'Mapa de mesas', descricao: 'Veja o status de cada mesa em tempo real.', icone: '🗺️' },
                { titulo: 'Divisão de conta', descricao: 'Divida por igual ou por consumo pelo celular.', icone: '➗' },
                { titulo: 'Envio instantâneo', descricao: 'Pedidos chegam na cozinha na hora.', icone: '⚡' },
              ],
            },
            'chatbot-para-delivery': {
              titulo: 'Chatbot para Delivery — Android',
              subtitulo: 'Acompanhe seu delivery pelo celular',
              descricao: 'Gerencie pedidos de delivery e acompanhe o chatbot do WhatsApp direto do app Android. Controle total na palma da mão.',
              icone: '🛵',
              recursos: [
                { titulo: 'Notificações de pedidos', descricao: 'Receba alertas de novos pedidos no celular.', icone: '🔔' },
                { titulo: 'Status em tempo real', descricao: 'Acompanhe cada pedido do início à entrega.', icone: '📍' },
                { titulo: 'Chatbot WhatsApp', descricao: 'Pedidos automáticos integrados ao app.', icone: '🤖' },
                { titulo: 'Gestão de entregas', descricao: 'Atribua entregadores direto do celular.', icone: '🏍️' },
              ],
            },
          },
          paginasSegmentos: {
            'restaurantes': {
              titulo: 'Mulherz Mobile para Restaurantes',
              subtitulo: 'Atendimento do salão na palma da mão',
              descricao: 'Com o app Mulherz para Android, garçons anotam pedidos, a cozinha recebe na hora e você acompanha tudo pelo celular.',
              icone: '🍽️',
              beneficios: [
                { titulo: 'App do garçom', descricao: 'Pedidos direto do celular para a cozinha.', icone: '📱' },
                { titulo: 'Mapa de mesas', descricao: 'Status do salão em tempo real.', icone: '🗺️' },
                { titulo: 'Notificações instantâneas', descricao: 'Alertas de novos pedidos e atualizações.', icone: '🔔' },
                { titulo: 'Dashboards mobile', descricao: 'Indicadores do negócio no celular.', icone: '📊' },
              ],
            },
            'sistema-para-delivery': {
              titulo: 'Mulherz Mobile para Delivery',
              subtitulo: 'Delivery gerenciado pelo Android',
              descricao: 'Acompanhe pedidos, gerencie entregadores e monitore o chatbot direto do app Android. Delivery profissional no seu bolso.',
              icone: '🛵',
              beneficios: [
                { titulo: 'Acompanhamento de pedidos', descricao: 'Status de cada pedido em tempo real.', icone: '📍' },
                { titulo: 'Gestão de entregadores', descricao: 'Atribua entregas direto do celular.', icone: '🏍️' },
                { titulo: 'Notificações push', descricao: 'Alertas instantâneos de novos pedidos.', icone: '🔔' },
                { titulo: 'Chatbot integrado', descricao: 'Pedidos do WhatsApp no app.', icone: '💬' },
              ],
            },
          },
          parceiros: {
            seloPagina: 'Programa de Parceiras',
            tituloPagina: 'Cresça com o Mulherz Mobile Android',
            subtituloPagina: 'Seja uma parceira e indique o app Mulherz para empreendedoras que precisam de mobilidade no Android.',
            seloSobre: 'Quem somos',
            tituloSobre: 'Conheça a Word System',
            descricaoSobre: 'Desenvolvemos apps móveis de gestão para empreendedoras do setor de alimentação.',
            descricaoEmpresa: 'Especializada em soluções mobile para restaurantes, bares, cafeterias e delivery.',
            sede: 'Maringá — PR, Brasil',
            cnpjLabel: 'Empresa registrada e ativa desde 2016',
            atuacao: 'Todo o território nacional',
            numeros: [
              { valor: '+10', rotulo: 'Anos no mercado', icone: '📅' },
              { valor: '+3.000', rotulo: 'Clientes ativas', icone: '👥' },
              { valor: '+15.000', rotulo: 'Estabelecimentos gerenciados', icone: '🏪' },
              { valor: '24/7', rotulo: 'Suporte disponível', icone: '🎧' },
            ],
            motivosParceiro: [
              'App Android leve e intuitivo para o dia a dia',
              'Produto feito para empreendedoras do setor de alimentação',
              'Mais de 3.000 clientes ativas em todo o Brasil',
              'Alta taxa de conversão — app gratuito na Play Store',
              'Suporte completo para fechar negócios',
              'Comissões recorrentes e previsíveis',
            ],
            vantagens: [
              { icone: '💰', titulo: 'Comissão Recorrente', descricao: 'Receba comissões mensais por cada cliente ativa indicada.' },
              { icone: '📦', titulo: 'Material de Apoio', descricao: 'Materiais de marketing focados no app Android.' },
              { icone: '🎓', titulo: 'Treinamento Especializado', descricao: 'Capacitação completa sobre o app mobile.' },
              { icone: '🤝', titulo: 'Suporte Dedicado', descricao: 'Canal direto com nosso time comercial.' },
              { icone: '📈', titulo: 'Painel da Parceira', descricao: 'Acompanhe indicações, comissões e desempenho.' },
              { icone: '🚀', titulo: 'Sem Investimento Inicial', descricao: 'Torne-se parceira sem nenhum custo.' },
            ],
            comoFunciona: [
              { passo: '1', titulo: 'Cadastre-se', descricao: 'Preencha o formulário e aguarde a aprovação.' },
              { passo: '2', titulo: 'Receba seu acesso', descricao: 'Após aprovada, acesse o painel e materiais de apoio.' },
              { passo: '3', titulo: 'Indique clientes', descricao: 'Compartilhe seu link e apresente o app Mulherz Android.' },
              { passo: '4', titulo: 'Receba comissões', descricao: 'A cada cliente que assinar, você recebe comissão recorrente.' },
            ],
            itensLateral: [
              'Comissão **recorrente** mensal',
              'Material de marketing **exclusivo**',
              'Treinamento **completo** sobre o app',
              'Suporte **dedicado** do time comercial',
              'Painel para acompanhar **indicações e ganhos**',
              '**Sem investimento** inicial',
            ],
            perfisIdeais: ['Consultoras de TI', 'Contadoras', 'Vendedoras autônomas', 'Empresas de tecnologia', 'Revendedoras de software'],
          },
        },
      },

      // ── iOS ──────────────────────────────────────────────────────────────
      'ios': {
        nome: 'Mulherz para iPhone',
        slogan: 'Seu negócio no iPhone',
        descricao: 'Baixe o app do Mulherz no iPhone e gerencie pedidos, mesas e mais direto do celular.',
        menus: {
          funcionalidades: {
            rotulo: "Funcionalidades",
            prefixoRota: "/funcionalidades",
            itens: [
              { rotulo: "Mesas e Comandas", slug: "mesas-e-comandas" },
              { rotulo: "Chatbot para Delivery", slug: "chatbot-para-delivery" },
            ],
          },
        },
        textos: {
          heroi: {
            selo: 'App nativo para iPhone',
            tituloAntes: 'Seu negócio no',
            tituloDestaque: 'iPhone',
            subtitulo: 'Com o app Mulherz para iOS, garçons anotam pedidos, a cozinha recebe na hora e você acompanha de qualquer lugar.',
            ctaPrimario: 'Baixar na App Store',
            ctaSecundario: 'Conhecer o sistema',
          },
          funcionalidades: {
            titulo: 'Tudo no seu iPhone',
            subtitulo: 'App nativo otimizado para iOS com a simplicidade que você merece.',
            cartoes: [
              { icone: '📱', titulo: 'App do Garçom', descricao: 'Anote pedidos direto no iPhone e envie para a cozinha instantaneamente.' },
              { icone: '🛵', titulo: 'Delivery no Celular', descricao: 'Acompanhe pedidos de delivery em tempo real.' },
              { icone: '📊', titulo: 'Dashboards Mobile', descricao: 'Indicadores do seu negócio na palma da mão.' },
            ],
          },
          chamadaFinal: {
            selo: 'Grátis na App Store',
            titulo: 'Baixe agora no seu iPhone',
            subtitulo: 'App gratuito com teste de {trialDays} dias de todos os módulos.',
            ctaPrimario: 'Baixar na App Store',
            ctaSecundario: 'Ver planos e preços',
          },
          planos: {
            seloHeroi: 'dias grátis, sem cartão de crédito',
            tituloHeroi: 'Mulherz para iPhone: seu negócio no bolso',
            subtituloHeroi: 'Baixe o app na App Store e teste por {trialDays} dias grátis. Gerencie mesas, pedidos e delivery direto do iPhone.',
          },
          paginasFuncionalidades: {
            'mesas-e-comandas': {
              titulo: 'Mesas e Comandas — iPhone',
              subtitulo: 'Atendimento elegante direto do iPhone',
              descricao: 'Gerencie mesas e comandas pelo app otimizado para iOS. Garçons anotam pedidos e enviam para a cozinha com a fluidez do iPhone.',
              icone: '🧾',
              recursos: [
                { titulo: 'App do garçom', descricao: 'Anote pedidos direto no iPhone com interface nativa.', icone: '📱' },
                { titulo: 'Mapa de mesas', descricao: 'Veja o status de cada mesa em tempo real.', icone: '🗺️' },
                { titulo: 'Divisão de conta', descricao: 'Divida por igual ou por consumo pelo iPhone.', icone: '➗' },
                { titulo: 'Envio instantâneo', descricao: 'Pedidos chegam na cozinha na hora.', icone: '⚡' },
              ],
            },
            'chatbot-para-delivery': {
              titulo: 'Chatbot para Delivery — iPhone',
              subtitulo: 'Delivery na palma da mão com iOS',
              descricao: 'Gerencie pedidos de delivery e acompanhe o chatbot do WhatsApp direto do app no iPhone. Experiência fluida e intuitiva.',
              icone: '🛵',
              recursos: [
                { titulo: 'Notificações de pedidos', descricao: 'Receba alertas de novos pedidos no iPhone.', icone: '🔔' },
                { titulo: 'Status em tempo real', descricao: 'Acompanhe cada pedido do início à entrega.', icone: '📍' },
                { titulo: 'Chatbot WhatsApp', descricao: 'Pedidos automáticos integrados ao app.', icone: '🤖' },
                { titulo: 'Gestão de entregas', descricao: 'Atribua entregadores direto do iPhone.', icone: '🏍️' },
              ],
            },
          },
          paginasSegmentos: {
            'restaurantes': {
              titulo: 'Mulherz Mobile para Restaurantes — iPhone',
              subtitulo: 'Atendimento do salão direto do iPhone',
              descricao: 'Com o app Mulherz para iOS, garçons anotam pedidos com a fluidez do iPhone e a cozinha recebe na hora.',
              icone: '🍽️',
              beneficios: [
                { titulo: 'App do garçom', descricao: 'Pedidos direto do iPhone para a cozinha.', icone: '📱' },
                { titulo: 'Mapa de mesas', descricao: 'Status do salão em tempo real.', icone: '🗺️' },
                { titulo: 'Notificações instantâneas', descricao: 'Alertas nativos do iOS para novos pedidos.', icone: '🔔' },
                { titulo: 'Dashboards mobile', descricao: 'Indicadores do negócio na tela do iPhone.', icone: '📊' },
              ],
            },
            'sistema-para-delivery': {
              titulo: 'Mulherz Mobile para Delivery — iPhone',
              subtitulo: 'Delivery profissional no iPhone',
              descricao: 'Acompanhe pedidos, gerencie entregadores e monitore o chatbot direto do app iOS. Delivery completo no seu iPhone.',
              icone: '🛵',
              beneficios: [
                { titulo: 'Acompanhamento de pedidos', descricao: 'Status de cada pedido em tempo real.', icone: '📍' },
                { titulo: 'Gestão de entregadores', descricao: 'Atribua entregas direto do iPhone.', icone: '🏍️' },
                { titulo: 'Notificações push', descricao: 'Alertas nativos do iOS para novos pedidos.', icone: '🔔' },
                { titulo: 'Chatbot integrado', descricao: 'Pedidos do WhatsApp no app.', icone: '💬' },
              ],
            },
          },
          parceiros: {
            seloPagina: 'Programa de Parceiras',
            tituloPagina: 'Cresça com o Mulherz no iPhone',
            subtituloPagina: 'Seja uma parceira e indique o app Mulherz para empreendedoras que usam iPhone. Comissões recorrentes garantidas.',
            seloSobre: 'Quem somos',
            tituloSobre: 'Conheça a Word System',
            descricaoSobre: 'Desenvolvemos apps iOS de gestão para empreendedoras do setor de alimentação.',
            descricaoEmpresa: 'Especializada em soluções mobile para restaurantes, bares, cafeterias e delivery.',
            sede: 'Maringá — PR, Brasil',
            cnpjLabel: 'Empresa registrada e ativa desde 2016',
            atuacao: 'Todo o território nacional',
            numeros: [
              { valor: '+10', rotulo: 'Anos no mercado', icone: '📅' },
              { valor: '+3.000', rotulo: 'Clientes ativas', icone: '👥' },
              { valor: '+15.000', rotulo: 'Estabelecimentos gerenciados', icone: '🏪' },
              { valor: '24/7', rotulo: 'Suporte disponível', icone: '🎧' },
            ],
            motivosParceiro: [
              'App iOS nativo com experiência premium',
              'Produto feito para empreendedoras do setor de alimentação',
              'Mais de 3.000 clientes ativas em todo o Brasil',
              'Alta taxa de conversão — app gratuito na App Store',
              'Suporte completo para fechar negócios',
              'Comissões recorrentes e previsíveis',
            ],
            vantagens: [
              { icone: '💰', titulo: 'Comissão Recorrente', descricao: 'Receba comissões mensais por cada cliente ativa indicada.' },
              { icone: '📦', titulo: 'Material de Apoio', descricao: 'Materiais de marketing focados no app iPhone.' },
              { icone: '🎓', titulo: 'Treinamento Especializado', descricao: 'Capacitação completa sobre o app iOS.' },
              { icone: '🤝', titulo: 'Suporte Dedicado', descricao: 'Canal direto com nosso time comercial.' },
              { icone: '📈', titulo: 'Painel da Parceira', descricao: 'Acompanhe indicações, comissões e desempenho.' },
              { icone: '🚀', titulo: 'Sem Investimento Inicial', descricao: 'Torne-se parceira sem nenhum custo.' },
            ],
            comoFunciona: [
              { passo: '1', titulo: 'Cadastre-se', descricao: 'Preencha o formulário e aguarde a aprovação.' },
              { passo: '2', titulo: 'Receba seu acesso', descricao: 'Após aprovada, acesse o painel e materiais de apoio.' },
              { passo: '3', titulo: 'Indique clientes', descricao: 'Compartilhe seu link e apresente o app Mulherz para iPhone.' },
              { passo: '4', titulo: 'Receba comissões', descricao: 'A cada cliente que assinar, você recebe comissão recorrente.' },
            ],
            itensLateral: [
              'Comissão **recorrente** mensal',
              'Material de marketing **exclusivo**',
              'Treinamento **completo** sobre o app',
              'Suporte **dedicado** do time comercial',
              'Painel para acompanhar **indicações e ganhos**',
              '**Sem investimento** inicial',
            ],
            perfisIdeais: ['Consultoras de TI', 'Contadoras', 'Vendedoras autônomas', 'Empresas de tecnologia', 'Revendedoras de software'],
          },
        },
      },
    },

    menus: {
      funcionalidades: {
        rotulo: "Funcionalidades",
        prefixoRota: "/funcionalidades",
        itens: [
          { rotulo: "Frente de Caixa (PDV)", slug: "frente-de-caixa-pdv" },
          { rotulo: "Mesas e Comandas", slug: "mesas-e-comandas" },
          { rotulo: "Chatbot para Delivery", slug: "chatbot-para-delivery" },
          { rotulo: "Financeiro", slug: "financeiro" },
          { rotulo: "Emissão Fiscal", slug: "emissao-fiscal" },
          { rotulo: "Relatórios Gerenciais", slug: "relatorios-gerenciais" },
        ],
      },
      segmentos: {
        rotulo: "Segmentos",
        prefixoRota: "/segmentos",
        itens: [
          { rotulo: "Restaurantes", slug: "restaurantes" },
          { rotulo: "Bares e Baladas", slug: "bares-e-baladas" },
          { rotulo: "Cafeterias", slug: "cafeterias" },
          { rotulo: "Dark Kitchens", slug: "dark-kitchens" },
          { rotulo: "Sistema para Delivery", slug: "sistema-para-delivery" },
        ],
      },
      plataformas: {
        rotulo: "Plataformas",
        prefixoRota: "/plataformas",
        itens: [
          { rotulo: "Windows", slug: "windows" },
          { rotulo: "Mac", slug: "mac" },
          { rotulo: "Linux", slug: "linux" },
          { rotulo: "Android", slug: "android" },
          { rotulo: "iOS", slug: "ios" },
        ],
      },
    },

    contato: {
      urlWhatsapp: "https://wa.me/5500000000002",
      email: "contato@mulherz.com.br",
    },

    suporte: {
      horarios: {
        diasUteis: "08h – 18h",
        sabado: "09h – 13h",
      },
    },

    links: {
      sistemaWeb: "https://app.mulherz.com.br/",
      appStore: URL_APP_STORE,
      playStore: URL_PLAY_STORE,
    },

    download: {
      categorias: [
        { chave: "sistema_principal", rotulo: "Sistema Principal", descricao: "Desktop" },
        { chave: "app_garcom", rotulo: "App Mobile", descricao: "Android / iPhone" },
      ],
      itens: [
        {
          id: "sistema-principal-windows",
          chavePlataforma: "windows",
          chaveCategoria: "sistema_principal",
          rotulo: "Windows",
          versao: "Windows 10 / 11 (64-bit)",
          tamanho: "TODO MB",
          urlDownload: "#",
          corBadge: "#0078D4",
        },
        {
          id: "app-mobile-android",
          chavePlataforma: "android",
          chaveCategoria: "app_garcom",
          rotulo: "Android",
          versao: "Android 8.0 ou superior",
          tamanho: "TODO MB",
          urlDownload: URL_PLAY_STORE,
          corBadge: "#34A853",
        },
        {
          id: "app-mobile-ios",
          chavePlataforma: "ios",
          chaveCategoria: "app_garcom",
          rotulo: "iPhone / iPad",
          versao: "iOS 15 ou superior",
          tamanho: "TODO MB",
          urlDownload: URL_APP_STORE,
          corBadge: "#000000",
        },
      ],
      requisitos: {
        desktop: [
          { rotulo: "Sistema operacional", minimo: "Windows 10 / macOS 12", recomendado: "Windows 11 / macOS 14" },
          { rotulo: "Processador", minimo: "Intel i3 / AMD Ryzen 3", recomendado: "Intel i5 / AMD Ryzen 5 ou superior" },
          { rotulo: "Memória RAM", minimo: "4 GB", recomendado: "8 GB ou mais" },
          { rotulo: "Armazenamento", minimo: "5 GB livres", recomendado: "20 GB livres (SSD)" },
          { rotulo: "Conexão", minimo: "2 Mbps", recomendado: "10 Mbps ou mais" },
        ],
        celular: [
          { rotulo: "Sistema operacional", minimo: "Android 8.0 / iOS 15", recomendado: "Android 12+ / iOS 17+" },
          { rotulo: "Processador", minimo: "Quad-core 1.6 GHz", recomendado: "Octa-core 2.0 GHz ou superior" },
          { rotulo: "Memória RAM", minimo: "2 GB", recomendado: "4 GB ou mais" },
          { rotulo: "Armazenamento", minimo: "200 MB livres", recomendado: "1 GB livres" },
          { rotulo: "Conexão", minimo: "Wi-Fi 2.4 GHz / 4G", recomendado: "Wi-Fi 5 GHz / 4G+ ou 5G" },
        ],
      },
    },
  },

  textos: {
    heroi: {
      selo: "A plataforma feita para empreendedoras de sucesso",
      tituloAntes: "Venda mais e gerencie",
      tituloDestaque: "do seu jeito",
      subtitulo: "Do atendimento ao financeiro, tudo em um só lugar — pensado para o seu negócio crescer.",
      ctaPrimario: "Começar {trialDays} dias grátis",
      ctaSecundario: "Conhecer o sistema",
    },
    appGarcom: {
      selo: "Aplicativo Nativo",
      titulo: "Seu atendente anota, o sistema",
      tituloDestaque: "já organiza.",
      subtitulo: "Aposte na tecnologia para agilizar o atendimento e encantar mais clientes todos os dias.",
      recursos: [
        { titulo: "Pedidos na hora", descricao: "Envio imediato para cozinha ou bar, sem papel e sem confusão." },
        { titulo: "Fechamento Simples", descricao: "Divida a conta facilmente e finalize o pagamento pelo próprio celular." },
      ],
    },
    funcionalidades: {
      titulo: "Tudo que você precisa para decolar",
      subtitulo: "Gestão completa, simples e bonita como você merece.",
      cartoes: [
        { icone: "🏪", titulo: "PDV e Balcão", descricao: "Atendimento rápido e eficiente com suporte a código de barras e balanças." },
        { icone: "🧾", titulo: "Mesas e Comandas", descricao: "Organize seu salão com comandas individuais e divisão de conta sem estresse." },
        { icone: "🛵", titulo: "Delivery Próprio", descricao: "Seu próprio canal de delivery, sem taxas para terceiros comendo seu lucro." },
        { icone: "💰", titulo: "Financeiro Completo", descricao: "Saiba exatamente quanto entra e quanto sai, a qualquer hora, em qualquer lugar." },
        { icone: "📑", titulo: "Nota Fiscal", descricao: "Emita NFC-e e NF-e de forma simples, integrada e sem complicação." },
        { icone: "📊", titulo: "Relatórios Inteligentes", descricao: "Veja seus produtos campeões, ticket médio e desempenho do negócio em tempo real." },
      ],
    },
    estatisticas: {
      selo: "Resultados que empoderam",
      titulo: "Números que fazem a diferença",
      itens: [
        { valor: "800+", rotulo: "Negócios ativos", icone: "🏪" },
        { valor: "97%", rotulo: "Taxa de satisfação", icone: "⭐" },
        { valor: "30%", rotulo: "Mais vendas em média", icone: "📈" },
        { valor: "3 anos", rotulo: "No mercado", icone: "🏆" },
      ],
      depoimentos: [
        { citacao: "Finalmente um sistema que eu consigo usar sem precisar de ajuda! Simples, bonito e completo.", nome: "Fernanda Lima", papel: "Proprietária — Café Sweet Pink, SP", iniciais: "FL" },
        { citacao: "Meu delivery cresceu 40% depois que migrei para o Mulherz. O controle é incrível.", nome: "Juliana Rocha", papel: "Empreendedora — Doceria da Ju, RJ", iniciais: "JR" },
        { citacao: "O suporte é maravilhoso e o sistema é muito fácil. Me sinto confiante gerenciando tudo.", nome: "Priscila Neves", papel: "Sócia — Bistrô Rosé, BH", iniciais: "PN" },
      ],
    },
    suporte: {
      selo: "Suporte com carinho",
      titulo: "Você nunca está sozinha",
      subtitulo: "Nossa equipe está sempre disponível para te ajudar a crescer sem stress e sem complicação.",
      cartoes: [
        { icone: "📞", titulo: "Suporte por WhatsApp", descricao: "Fale com a nossa equipe pelo WhatsApp e receba ajuda rápida, sem burocracia." },
        {
          icone: "💻",
          titulo: "Acesso Remoto",
          descricao: "Resolvemos qualquer problema diretamente no seu computador, sem você precisar explicar nada.",
          destaque: true,
          rotuloDestaque: "exclusivo",
        },
        { icone: "🎓", titulo: "Treinamento Completo", descricao: "Aprenda tudo sobre o sistema com nosso time de implantação. Do básico ao avançado." },
      ],
      tituloHorario: "Horário de atendimento",
      rotuloDomingo: "Domingo e feriados",
      valorDomingo: "Plantão",
      notaDomingo: "Urgências via WhatsApp",
      notaSuporteCompleto: "Suporte completo",
    },
    contato: {
      selo: "Fale com a gente",
      titulo: "Vamos conversar?",
      subtitulo: "Seja para tirar dúvidas, pedir uma demonstração ou conhecer nossos planos personalizados, estamos aqui.",
      rotuloWhatsapp: "WhatsApp Comercial",
      notaWhatsapp: "Resposta em minutos no horário de atendimento",
      rotuloEmail: "E-mail",
      textoBotaoFormulario: "Enviar mensagem via WhatsApp",
      notaFormulario: "Ao enviar, você será redirecionada ao WhatsApp com os dados preenchidos.",
    },
    chamadaFinal: {
      selo: "Sem cartão de crédito",
      titulo: "Pronta para transformar seu negócio?",
      subtitulo: "Teste o Mulherz por {trialDays} dias com tudo liberado, sem compromisso e de graça.",
      ctaPrimario: "Começar {trialDays} dias grátis",
      ctaSecundario: "Ver planos e preços",
    },
    cadastro: {
      seloTeste: "dias grátis · sem cartão",
      tituloFormulario: "Crie sua conta no Mulherz",
      subtituloFormulario: "Preencha os dados abaixo para começar agora mesmo.",
      campoEstabelecimento: "Nome do seu negócio",
      placeholderCampoEstabelecimento: "Ex: Doceria da Maria",
      seloRiscoLateral: "Sem risco",
      tituloLateral: "Seu negócio merece o melhor!",
      itensLateral: [
        "Sem precisar cadastrar cartão de crédito",
        "Acesso a **todos os módulos** durante o teste",
        "PDV, Mesas, Comandas, Delivery e NFC-e liberados",
        "Suporte humano durante seu período de teste",
        "Cancele quando quiser, sem burocracia",
      ],
      rotuloModulosLateral: "Módulos inclusos no teste:",
      modulosLateral: ["PDV Rápido", "Mesas", "Delivery", "Comandas", "NFC-e / NF-e", "Financeiro", "App Garçom", "Relatórios"],
    },
    baixar: {
      tituloSucesso: "Cadastro realizado!",
      subtituloSucesso: "Sua conta foi criada com sucesso. Agora baixe o sistema para começar.",
      rotuloAcessoWeb: "Ou acesse pelo navegador em",
    },
    download: {
      tituloSecao: "Baixar o Mulherz",
      prefixoOsDetectado: "Detectamos que você usa",
      osDesconhecido: "Escolha sua plataforma abaixo",
      prefixoBotaoDownload: "Baixar para",
      botaoOutrasPlataformas: "Baixar para outra plataforma",
      tituloPassos: "Como começar em 3 passos",
      passos: [
        { titulo: "Baixe e instale", descricao: "Clique no botão acima, baixe o instalador e execute. Leva menos de 2 minutos." },
        { titulo: "Faça login", descricao: "Entre com seu e-mail e senha recém-cadastrados. Seus módulos já estão liberados." },
        { titulo: "Configure seu negócio", descricao: "Siga o assistente inicial e cadastre produtos, mesas e configure o delivery." },
      ],
      tituloRequisitos: "Requisitos do sistema",
      rotuloDesktop: "Computador (PDV / Painel)",
      rotuloMobile: "Celular (App Atendente)",
    },
    planos: {
      seloHeroi: "dias grátis, sem cartão de crédito",
      tituloHeroi: "Mulherz: o plano ideal para o seu negócio crescer",
      subtituloHeroi: "Comece gratuitamente por {trialDays} dias, sem cartão, e explore todos os recursos.",
    },
    paginasFuncionalidades: {
      "frente-de-caixa-pdv": {
        titulo: "Frente de Caixa (PDV)",
        subtitulo: "Atendimento ágil e eficiente",
        descricao: "O PDV do Mulherz foi feito para quem precisa de velocidade no atendimento. Leitura de código de barras, balanças e fechamento rápido.",
        icone: "🏪",
        recursos: [
          { titulo: "Leitura de código de barras", descricao: "Escaneie produtos e agilize o atendimento.", icone: "📷" },
          { titulo: "Integração com balanças", descricao: "Peso direto no sistema, sem digitação.", icone: "⚖️" },
          { titulo: "Múltiplas formas de pagamento", descricao: "Dinheiro, cartão, Pix e vouchers.", icone: "💳" },
          { titulo: "Modo offline", descricao: "Venda sem internet — sincroniza depois.", icone: "📶" },
        ],
      },
      "mesas-e-comandas": {
        titulo: "Mesas e Comandas",
        subtitulo: "Organize seu salão com elegância",
        descricao: "Gerencie mesas, comandas e divisão de contas de forma simples e visual. Perfeito para o dia a dia do seu negócio.",
        icone: "🧾",
        recursos: [
          { titulo: "Mapa de mesas visual", descricao: "Veja o status de cada mesa em tempo real.", icone: "🗺️" },
          { titulo: "Comandas individuais", descricao: "Cada cliente com sua comanda.", icone: "📝" },
          { titulo: "Divisão de conta", descricao: "Divida por igual ou por consumo individual.", icone: "➗" },
          { titulo: "Transferência de mesa", descricao: "Mova clientes sem perder pedidos.", icone: "🔄" },
        ],
      },
      "chatbot-para-delivery": {
        titulo: "Chatbot para Delivery",
        subtitulo: "Seu delivery automatizado",
        descricao: "Receba pedidos pelo WhatsApp e pelo seu próprio site, sem comissões. Chatbot inteligente para atender seus clientes 24h.",
        icone: "🛵",
        recursos: [
          { titulo: "Cardápio digital", descricao: "Seu cardápio online sempre atualizado.", icone: "📱" },
          { titulo: "Chatbot WhatsApp", descricao: "Atendimento automático 24h.", icone: "🤖" },
          { titulo: "Acompanhamento de pedido", descricao: "Status em tempo real para o cliente.", icone: "📍" },
          { titulo: "Integração com marketplaces", descricao: "iFood e outros integrados ao sistema.", icone: "🔗" },
        ],
      },
      "financeiro": {
        titulo: "Financeiro",
        subtitulo: "Suas finanças sob controle",
        descricao: "Controle receitas, despesas e fluxo de caixa com simplicidade. Tudo que você precisa para manter o financeiro organizado.",
        icone: "💰",
        recursos: [
          { titulo: "Fluxo de caixa", descricao: "Entradas e saídas em tempo real.", icone: "📊" },
          { titulo: "Contas a pagar e receber", descricao: "Organize vencimentos e cobranças.", icone: "📅" },
          { titulo: "Conciliação bancária", descricao: "Compare com o extrato do banco.", icone: "🏦" },
          { titulo: "DRE automático", descricao: "Resultados gerados automaticamente.", icone: "📈" },
        ],
      },
      "emissao-fiscal": {
        titulo: "Emissão Fiscal",
        subtitulo: "Notas fiscais sem complicação",
        descricao: "Emita NFC-e e NF-e diretamente pelo sistema. Conformidade fiscal total sem dor de cabeça.",
        icone: "📑",
        recursos: [
          { titulo: "NFC-e automática", descricao: "Nota de consumidor gerada a cada venda.", icone: "🧾" },
          { titulo: "NF-e completa", descricao: "Nota eletrônica para fornecedores e clientes.", icone: "📄" },
          { titulo: "Cancelamento e inutilização", descricao: "Gerencie notas canceladas facilmente.", icone: "❌" },
          { titulo: "Relatório fiscal", descricao: "Consulte notas com filtros avançados.", icone: "🔍" },
        ],
      },
      "relatorios-gerenciais": {
        titulo: "Relatórios Gerenciais",
        subtitulo: "Decisões baseadas em dados",
        descricao: "Dashboards e relatórios com ticket médio, ranking de produtos e indicadores atualizados em tempo real.",
        icone: "📊",
        recursos: [
          { titulo: "Dashboard em tempo real", descricao: "Indicadores atualizados automaticamente.", icone: "📈" },
          { titulo: "Ticket médio", descricao: "Valor médio das vendas por período.", icone: "🎫" },
          { titulo: "Ranking de produtos", descricao: "Seus campeões de venda em destaque.", icone: "🏆" },
          { titulo: "Relatório por atendente", descricao: "Performance individual da equipe.", icone: "👤" },
        ],
      },
    },
    paginasSegmentos: {
      "restaurantes": {
        titulo: "Sistema para Restaurantes",
        subtitulo: "Tudo que seu restaurante precisa",
        descricao: "Do salão ao delivery, o Mulherz oferece uma gestão completa e intuitiva para o seu restaurante.",
        icone: "🍽️",
        beneficios: [
          { titulo: "Gestão de mesas e comandas", descricao: "Mapa visual e comandas individuais.", icone: "🗺️" },
          { titulo: "PDV rápido", descricao: "Atendimento no caixa em segundos.", icone: "🏪" },
          { titulo: "Delivery integrado", descricao: "Canal próprio sem taxas abusivas.", icone: "🛵" },
          { titulo: "Emissão fiscal automática", descricao: "NFC-e e NF-e integradas.", icone: "📑" },
        ],
      },
      "bares-e-baladas": {
        titulo: "Sistema para Bares e Baladas",
        subtitulo: "Velocidade para a noite",
        descricao: "Comandas rápidas, estoque de bebidas e atendimento em alta velocidade para bares e casas noturnas.",
        icone: "🍺",
        beneficios: [
          { titulo: "Comandas rápidas", descricao: "Abertura e fechamento instantâneos.", icone: "⚡" },
          { titulo: "Controle de estoque", descricao: "Monitore bebidas em tempo real.", icone: "📦" },
          { titulo: "Divisão de conta", descricao: "Divida por igual ou por consumo.", icone: "➗" },
          { titulo: "App do garçom", descricao: "Pedidos direto do celular.", icone: "📱" },
        ],
      },
      "cafeterias": {
        titulo: "Sistema para Cafeterias",
        subtitulo: "Praticidade para o seu café",
        descricao: "PDV rápido, controle de insumos e relatórios para otimizar sua cafeteria.",
        icone: "☕",
        beneficios: [
          { titulo: "PDV de balcão", descricao: "Atendimento rápido e eficiente.", icone: "🏪" },
          { titulo: "Programa de fidelidade", descricao: "Cartão digital de pontos.", icone: "⭐" },
          { titulo: "Controle de insumos", descricao: "Saiba o custo de cada receita.", icone: "📊" },
          { titulo: "Relatórios de vendas", descricao: "Identifique seus campeões de venda.", icone: "📈" },
        ],
      },
      "dark-kitchens": {
        titulo: "Sistema para Dark Kitchens",
        subtitulo: "Foco total em delivery",
        descricao: "Automatize pedidos, integre com marketplaces e otimize sua cozinha com o Mulherz.",
        icone: "🏭",
        beneficios: [
          { titulo: "Integração com marketplaces", descricao: "Pedidos de todos os canais centralizados.", icone: "🔗" },
          { titulo: "Chatbot WhatsApp", descricao: "Pedidos automáticos 24h.", icone: "🤖" },
          { titulo: "Painel de produção", descricao: "Organize pedidos por prioridade.", icone: "📋" },
          { titulo: "Relatório de performance", descricao: "Tempo de preparo e métricas.", icone: "📊" },
        ],
      },
      "sistema-para-delivery": {
        titulo: "Sistema para Delivery",
        subtitulo: "Seu delivery sem taxas abusivas",
        descricao: "Cardápio digital, chatbot e integração com marketplaces. Delivery profissional com a sua marca.",
        icone: "🛵",
        beneficios: [
          { titulo: "Site próprio de delivery", descricao: "Cardápio online com sua marca.", icone: "🌐" },
          { titulo: "Chatbot para WhatsApp", descricao: "Pedidos automáticos pelo WhatsApp.", icone: "💬" },
          { titulo: "Rastreamento de pedido", descricao: "Status em tempo real.", icone: "📍" },
          { titulo: "Gestão de entregadores", descricao: "Controle rotas e atribuições.", icone: "🏍️" },
        ],
      },
    },
    parceiros: {
      seloPagina: "Programa de Parceiras",
      tituloPagina: "Cresça com o Mulherz",
      subtituloPagina: "Seja uma parceira comercial e ganhe comissões recorrentes indicando o sistema feito por mulheres para mulheres empreendedoras.",
      seloSobre: "Quem somos",
      tituloSobre: "Conheça a Word System",
      descricaoSobre: "Desenvolvemos soluções completas de gestão para mulheres que empreendem no setor de alimentação.",
      descricaoEmpresa: "Especializada no desenvolvimento de sistemas para bares, restaurantes, cafeterias e delivery.",
      sede: "Maringá — PR, Brasil",
      cnpjLabel: "Empresa registrada e ativa desde 2016",
      atuacao: "Todo o território nacional",
      numeros: [
        { valor: "+10", rotulo: "Anos no mercado", icone: "📅" },
        { valor: "+3.000", rotulo: "Clientes ativos", icone: "👥" },
        { valor: "+15.000", rotulo: "Estabelecimentos gerenciados", icone: "🏪" },
        { valor: "24/7", rotulo: "Suporte disponível", icone: "🎧" },
      ],
      motivosParceiro: [
        "Mercado de food service em constante crescimento",
        "Produto feito sob medida para mulheres empreendedoras",
        "Mais de 3.000 clientes ativos em todo o Brasil",
        "Alta taxa de conversão e retenção de clientes",
        "Suporte completo para fechar negócios",
        "Comissões recorrentes e previsíveis",
      ],
      vantagens: [
        { icone: "💰", titulo: "Comissão Recorrente", descricao: "Receba comissões mensais por cada cliente ativa indicada por você." },
        { icone: "📦", titulo: "Material de Apoio", descricao: "Acesso a materiais de marketing, apresentações e conteúdos exclusivos." },
        { icone: "🎓", titulo: "Treinamento Especializado", descricao: "Capacitação completa sobre o sistema para você vender com confiança." },
        { icone: "🤝", titulo: "Suporte Dedicado", descricao: "Canal direto com nosso time comercial para tirar dúvidas e fechar negócios." },
        { icone: "📈", titulo: "Painel da Parceira", descricao: "Acompanhe suas indicações, comissões e desempenho em tempo real." },
        { icone: "🚀", titulo: "Sem Investimento Inicial", descricao: "Torne-se parceira sem nenhum custo. Basta se cadastrar e começar." },
      ],
      comoFunciona: [
        { passo: "1", titulo: "Cadastre-se", descricao: "Preencha o formulário com seus dados e aguarde a aprovação." },
        { passo: "2", titulo: "Receba seu acesso", descricao: "Após aprovada, você terá acesso ao painel e materiais de apoio." },
        { passo: "3", titulo: "Indique clientes", descricao: "Compartilhe seu link exclusivo e apresente o Mulherz para potenciais clientes." },
        { passo: "4", titulo: "Receba comissões", descricao: "A cada cliente que assinar, você recebe comissão recorrente." },
      ],
      itensLateral: [
        "Comissão **recorrente** mensal",
        "Material de marketing **exclusivo**",
        "Treinamento **completo** sobre o produto",
        "Suporte **dedicado** do time comercial",
        "Painel para acompanhar **indicações e ganhos**",
        "**Sem investimento** inicial",
      ],
      perfisIdeais: ["Consultoras de TI", "Contadoras", "Vendedoras autônomas", "Empresas de tecnologia", "Revendedoras de software"],
    },
  },
};
